////
////  PokemonTypesTest.swift
////  PokeQuiz
////
////  Created by Tanner Garlick on 2/16/22.
////
//
//import Foundation
//
//struct PokemonTypes: Hashable {
//    // must be hashable in order to be a key in a dictionary
//
//    let name: String
//    let number: String
//    let type: [String]
//
//    static var allPokemon = [
//
//        PokemonTypes(name: "Bulbasaur", number: "001", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Ivysaur", number: "002", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Venusaur", number: "003", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Charmander", number: "004", type: ["Fire"]),
//        PokemonTypes(name: "Charmeleon", number: "005", type: ["Fire"]),
//        PokemonTypes(name: "Charizard", number: "006", type: ["Fire", "Flying"]),
//        PokemonTypes(name: "Squirtle", number: "007", type: ["Water"]),
//        PokemonTypes(name: "Wartortle", number: "008", type: ["Water"]),
//        PokemonTypes(name: "Blastoise", number: "009", type: ["Water"]),
//        PokemonTypes(name: "Caterpie", number: "010", type: ["Bug"]),
//        PokemonTypes(name: "Metapod", number: "011", type: ["Bug"]),
//        PokemonTypes(name: "Butterfree", number: "012", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Weedle", number: "013", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Kakuna", number: "014", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Beedrill", number: "015", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Pidgey", number: "016", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Pidgeotto", number: "017", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Pidgeot", number: "018", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Rattata", number: "019", type: ["Normal"]),
//        PokemonTypes(name: "Raticate", number: "020", type: ["Normal"]),
//        PokemonTypes(name: "Spearow", number: "021", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Fearow", number: "022", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Ekans", number: "023", type: ["Poison"]),
//        PokemonTypes(name: "Arbok", number: "024", type: ["Poison"]),
//        PokemonTypes(name: "Pikachu", number: "025", type: ["Electric"]),
//        PokemonTypes(name: "Raichu", number: "026", type: ["Electric"]),
//        PokemonTypes(name: "Sandshrew", number: "027", type: ["Ground"]),
//        PokemonTypes(name: "Sandslash", number: "028", type: ["Ground"]),
//        PokemonTypes(name: "Nidoran♀", number: "029", type: ["Poison"]),
//        PokemonTypes(name: "Nidorina", number: "030", type: ["Poison"]),
//        PokemonTypes(name: "Nidoqueen", number: "031", type: ["Poison", "Ground"]),
//        PokemonTypes(name: "Nidoran♂", number: "032", type: ["Poison"]),
//        PokemonTypes(name: "Nidorino", number: "033", type: ["Poison"]),
//        PokemonTypes(name: "Nidoking", number: "034", type: ["Poison", "Ground"]),
//        PokemonTypes(name: "Clefairy", number: "035", type: ["Fairy"]),
//        PokemonTypes(name: "Clefable", number: "036", type: ["Fairy"]),
//        PokemonTypes(name: "Vulpix", number: "037", type: ["Fire"]),
//        PokemonTypes(name: "Ninetales", number: "038", type: ["Fire"]),
//        PokemonTypes(name: "Jigglypuff", number: "039", type: ["Normal", "Fairy"]),
//        PokemonTypes(name: "Wigglytuff", number: "040", type: ["Normal", "Fairy"]),
//        PokemonTypes(name: "Zubat", number: "041", type: ["Poison", "Flying"]),
//        PokemonTypes(name: "Golbat", number: "042", type: ["Poison", "Flying"]),
//        PokemonTypes(name: "Oddish", number: "043", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Gloom", number: "044", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Vileplume", number: "045", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Paras", number: "046", type: ["Bug", "Grass"]),
//        PokemonTypes(name: "Parasect", number: "047", type: ["Bug", "Grass"]),
//        PokemonTypes(name: "Venonat", number: "048", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Venomoth", number: "049", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Diglett", number: "050", type: ["Ground"]),
//        PokemonTypes(name: "Dugtrio", number: "051", type: ["Ground"]),
//        PokemonTypes(name: "Meowth", number: "052", type: ["Normal"]),
//        PokemonTypes(name: "Persian", number: "053", type: ["Normal"]),
//        PokemonTypes(name: "Psyduck", number: "054", type: ["Water"]),
//        PokemonTypes(name: "Golduck", number: "055", type: ["Water"]),
//        PokemonTypes(name: "Mankey", number: "056", type: ["Fighting"]),
//        PokemonTypes(name: "Primeape", number: "057", type: ["Fighting"]),
//        PokemonTypes(name: "Growlithe", number: "058", type: ["Fire"]),
//        PokemonTypes(name: "Arcanine", number: "059", type: ["Fire"]),
//        PokemonTypes(name: "Poliwag", number: "060", type: ["Water"]),
//        PokemonTypes(name: "Poliwhirl", number: "061", type: ["Water"]),
//        PokemonTypes(name: "Poliwrath", number: "062", type: ["Water", "Fighting"]),
//        PokemonTypes(name: "Abra", number: "063", type: ["Psychic"]),
//        PokemonTypes(name: "Kadabra", number: "064", type: ["Psychic"]),
//        PokemonTypes(name: "Alakazam", number: "065", type: ["Psychic"]),
//        PokemonTypes(name: "Machop", number: "066", type: ["Fighting"]),
//        PokemonTypes(name: "Machoke", number: "067", type: ["Fighting"]),
//        PokemonTypes(name: "Machamp", number: "068", type: ["Fighting"]),
//        PokemonTypes(name: "Bellsprout", number: "069", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Weepinbell", number: "070", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Victreebel", number: "071", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Tentacool", number: "072", type: ["Water", "Poison"]),
//        PokemonTypes(name: "Tentacruel", number: "073", type: ["Water", "Poison"]),
//        PokemonTypes(name: "Geodude", number: "074", type: ["Rock", "Ground"]),
//        PokemonTypes(name: "Graveler", number: "075", type: ["Rock", "Ground"]),
//        PokemonTypes(name: "Golem", number: "076", type: ["Rock", "Ground"]),
//        PokemonTypes(name: "Ponyta", number: "077", type: ["Fire"]),
//        PokemonTypes(name: "Rapidash", number: "078", type: ["Fire"]),
//        PokemonTypes(name: "Slowpoke", number: "079", type: ["Water", "Psychic"]),
//        PokemonTypes(name: "Slowbro", number: "080", type: ["Water", "Psychic"]),
//        PokemonTypes(name: "Magnemite", number: "081", type: ["Electric", "Steel"]),
//        PokemonTypes(name: "Magneton", number: "082", type: ["Electric", "Steel"]),
//        PokemonTypes(name: "Farfetch’d", number: "083", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Doduo", number: "084", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Dodrio", number: "085", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Seel", number: "086", type: ["Water"]),
//        PokemonTypes(name: "Dewgong", number: "087", type: ["Water", "Ice"]),
//        PokemonTypes(name: "Grimer", number: "088", type: ["Poison"]),
//        PokemonTypes(name: "Muk", number: "089", type: ["Poison"]),
//        PokemonTypes(name: "Shellder", number: "090", type: ["Water"]),
//        PokemonTypes(name: "Cloyster", number: "091", type: ["Water", "Ice"]),
//        PokemonTypes(name: "Gastly", number: "092", type: ["Ghost", "Poison"]),
//        PokemonTypes(name: "Haunter", number: "093", type: ["Ghost", "Poison"]),
//        PokemonTypes(name: "Gengar", number: "094", type: ["Ghost", "Poison"]),
//        PokemonTypes(name: "Onix", number: "095", type: ["Rock", "Ground"]),
//        PokemonTypes(name: "Drowzee", number: "096", type: ["Psychic"]),
//        PokemonTypes(name: "Hypno", number: "097", type: ["Psychic"]),
//        PokemonTypes(name: "Krabby", number: "098", type: ["Water"]),
//        PokemonTypes(name: "Kingler", number: "099", type: ["Water"]),
//        PokemonTypes(name: "Voltorb", number: "100", type: ["Electric"]),
//        PokemonTypes(name: "Electrode", number: "101", type: ["Electric"]),
//        PokemonTypes(name: "Exeggcute", number: "102", type: ["Grass", "Psychic"]),
//        PokemonTypes(name: "Exeggutor", number: "103", type: ["Grass", "Psychic"]),
//        PokemonTypes(name: "Cubone", number: "104", type: ["Ground"]),
//        PokemonTypes(name: "Marowak", number: "105", type: ["Ground"]),
//        PokemonTypes(name: "Hitmonlee", number: "106", type: ["Fighting"]),
//        PokemonTypes(name: "Hitmonchan", number: "107", type: ["Fighting"]),
//        PokemonTypes(name: "Lickitung", number: "108", type: ["Normal"]),
//        PokemonTypes(name: "Koffing", number: "109", type: ["Poison"]),
//        PokemonTypes(name: "Weezing", number: "110", type: ["Poison"]),
//        PokemonTypes(name: "Rhyhorn", number: "111", type: ["Ground", "Rock"]),
//        PokemonTypes(name: "Rhydon", number: "112", type: ["Ground", "Rock"]),
//        PokemonTypes(name: "Chansey", number: "113", type: ["Normal"]),
//        PokemonTypes(name: "Tangela", number: "114", type: ["Grass"]),
//        PokemonTypes(name: "Kangaskhan", number: "115", type: ["Normal"]),
//        PokemonTypes(name: "Horsea", number: "116", type: ["Water"]),
//        PokemonTypes(name: "Seadra", number: "117", type: ["Water"]),
//        PokemonTypes(name: "Goldeen", number: "118", type: ["Water"]),
//        PokemonTypes(name: "Seaking", number: "119", type: ["Water"]),
//        PokemonTypes(name: "Staryu", number: "120", type: ["Water"]),
//        PokemonTypes(name: "Starmie", number: "121", type: ["Water", "Psychic"]),
//        PokemonTypes(name: "Mr. Mime", number: "122", type: ["Psychic", "Fairy"]),
//        PokemonTypes(name: "Scyther", number: "123", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Jynx", number: "124", type: ["Ice", "Psychic"]),
//        PokemonTypes(name: "Electabuzz", number: "125", type: ["Electric"]),
//        PokemonTypes(name: "Magmar", number: "126", type: ["Fire"]),
//        PokemonTypes(name: "Pinsir", number: "127", type: ["Bug"]),
//        PokemonTypes(name: "Tauros", number: "128", type: ["Normal"]),
//        PokemonTypes(name: "Magikarp", number: "129", type: ["Water"]),
//        PokemonTypes(name: "Gyarados", number: "130", type: ["Water", "Flying"]),
//        PokemonTypes(name: "Lapras", number: "131", type: ["Water", "Ice"]),
//        PokemonTypes(name: "Ditto", number: "132", type: ["Normal"]),
//        PokemonTypes(name: "Eevee", number: "133", type: ["Normal"]),
//        PokemonTypes(name: "Vaporeon", number: "134", type: ["Water"]),
//        PokemonTypes(name: "Jolteon", number: "135", type: ["Electric"]),
//        PokemonTypes(name: "Flareon", number: "136", type: ["Fire"]),
//        PokemonTypes(name: "Porygon", number: "137", type: ["Normal"]),
//        PokemonTypes(name: "Omanyte", number: "138", type: ["Rock", "Water"]),
//        PokemonTypes(name: "Omastar", number: "139", type: ["Rock", "Water"]),
//        PokemonTypes(name: "Kabuto", number: "140", type: ["Rock", "Water"]),
//        PokemonTypes(name: "Kabutops", number: "141", type: ["Rock", "Water"]),
//        PokemonTypes(name: "Aerodactyl", number: "142", type: ["Rock", "Flying"]),
//        PokemonTypes(name: "Snorlax", number: "143", type: ["Normal"]),
//        PokemonTypes(name: "Articuno", number: "144", type: ["Ice", "Flying"]),
//        PokemonTypes(name: "Zapdos", number: "145", type: ["Electric", "Flying"]),
//        PokemonTypes(name: "Moltres", number: "146", type: ["Fire", "Flying"]),
//        PokemonTypes(name: "Dratini", number: "147", type: ["Dragon"]),
//        PokemonTypes(name: "Dragonair", number: "148", type: ["Dragon"]),
//        PokemonTypes(name: "Dragonite", number: "149", type: ["Dragon", "Flying"]),
//        PokemonTypes(name: "Mewtwo", number: "150", type: ["Psychic"]),
//        PokemonTypes(name: "Mew", number: "151", type: ["Psychic"]),
//        PokemonTypes(name: "Chikorita", number: "152", type: ["Grass"]),
//        PokemonTypes(name: "Bayleef", number: "153", type: ["Grass"]),
//        PokemonTypes(name: "Meganium", number: "154", type: ["Grass"]),
//        PokemonTypes(name: "Cyndaquil", number: "155", type: ["Fire"]),
//        PokemonTypes(name: "Quilava", number: "156", type: ["Fire"]),
//        PokemonTypes(name: "Typhlosion", number: "157", type: ["Fire"]),
//        PokemonTypes(name: "Totodile", number: "158", type: ["Water"]),
//        PokemonTypes(name: "Croconaw", number: "159", type: ["Water"]),
//        PokemonTypes(name: "Feraligatr", number: "160", type: ["Water"]),
//        PokemonTypes(name: "Sentret", number: "161", type: ["Normal"]),
//        PokemonTypes(name: "Furret", number: "162", type: ["Normal"]),
//        PokemonTypes(name: "Hoothoot", number: "163", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Noctowl", number: "164", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Ledyba", number: "165", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Ledian", number: "166", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Spinarak", number: "167", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Ariados", number: "168", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Crobat", number: "169", type: ["Poison", "Flying"]),
//        PokemonTypes(name: "Chinchou", number: "170", type: ["Water", "Electric"]),
//        PokemonTypes(name: "Lanturn", number: "171", type: ["Water", "Electric"]),
//        PokemonTypes(name: "Pichu", number: "172", type: ["Electric"]),
//        PokemonTypes(name: "Cleffa", number: "173", type: ["Fairy"]),
//        PokemonTypes(name: "Igglybuff", number: "174", type: ["Normal", "Fairy"]),
//        PokemonTypes(name: "Togepi", number: "175", type: ["Fairy"]),
//        PokemonTypes(name: "Togetic", number: "176", type: ["Fairy", "Flying"]),
//        PokemonTypes(name: "Natu", number: "177", type: ["Psychic", "Flying"]),
//        PokemonTypes(name: "Xatu", number: "178", type: ["Psychic", "Flying"]),
//        PokemonTypes(name: "Mareep", number: "179", type: ["Electric"]),
//        PokemonTypes(name: "Flaaffy", number: "180", type: ["Electric"]),
//        PokemonTypes(name: "Ampharos", number: "181", type: ["Electric"]),
//        PokemonTypes(name: "Bellossom", number: "182", type: ["Grass"]),
//        PokemonTypes(name: "Marill", number: "183", type: ["Water", "Fairy"]),
//        PokemonTypes(name: "Azumarill", number: "184", type: ["Water", "Fairy"]),
//        PokemonTypes(name: "Sudowoodo", number: "185", type: ["Rock"]),
//        PokemonTypes(name: "Politoed", number: "186", type: ["Water"]),
//        PokemonTypes(name: "Hoppip", number: "187", type: ["Grass", "Flying"]),
//        PokemonTypes(name: "Skiploom", number: "188", type: ["Grass", "Flying"]),
//        PokemonTypes(name: "Jumpluff", number: "189", type: ["Grass", "Flying"]),
//        PokemonTypes(name: "Aipom", number: "190", type: ["Normal"]),
//        PokemonTypes(name: "Sunkern", number: "191", type: ["Grass"]),
//        PokemonTypes(name: "Sunflora", number: "192", type: ["Grass"]),
//        PokemonTypes(name: "Yanma", number: "193", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Wooper", number: "194", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Quagsire", number: "195", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Espeon", number: "196", type: ["Psychic"]),
//        PokemonTypes(name: "Umbreon", number: "197", type: ["Dark"]),
//        PokemonTypes(name: "Murkrow", number: "198", type: ["Dark", "Flying"]),
//        PokemonTypes(name: "Slowking", number: "199", type: ["Water", "Psychic"]),
//        PokemonTypes(name: "Misdreavus", number: "200", type: ["Ghost"]),
//        PokemonTypes(name: "Unown", number: "201", type: ["Psychic"]),
//        PokemonTypes(name: "Wobbuffet", number: "202", type: ["Psychic"]),
//        PokemonTypes(name: "Girafarig", number: "203", type: ["Normal", "Psychic"]),
//        PokemonTypes(name: "Pineco", number: "204", type: ["Bug"]),
//        PokemonTypes(name: "Forretress", number: "205", type: ["Bug", "Steel"]),
//        PokemonTypes(name: "Dunsparce", number: "206", type: ["Normal"]),
//        PokemonTypes(name: "Gligar", number: "207", type: ["Ground", "Flying"]),
//        PokemonTypes(name: "Steelix", number: "208", type: ["Steel", "Ground"]),
//        PokemonTypes(name: "Snubbull", number: "209", type: ["Fairy"]),
//        PokemonTypes(name: "Granbull", number: "210", type: ["Fairy"]),
//        PokemonTypes(name: "Qwilfish", number: "211", type: ["Water", "Poison"]),
//        PokemonTypes(name: "Scizor", number: "212", type: ["Bug", "Steel"]),
//        PokemonTypes(name: "Shuckle", number: "213", type: ["Bug", "Rock"]),
//        PokemonTypes(name: "Heracross", number: "214", type: ["Bug", "Fighting"]),
//        PokemonTypes(name: "Sneasel", number: "215", type: ["Dark", "Ice"]),
//        PokemonTypes(name: "Teddiursa", number: "216", type: ["Normal"]),
//        PokemonTypes(name: "Ursaring", number: "217", type: ["Normal"]),
//        PokemonTypes(name: "Slugma", number: "218", type: ["Fire"]),
//        PokemonTypes(name: "Magcargo", number: "219", type: ["Fire", "Rock"]),
//        PokemonTypes(name: "Swinub", number: "220", type: ["Ice", "Ground"]),
//        PokemonTypes(name: "Piloswine", number: "221", type: ["Ice", "Ground"]),
//        PokemonTypes(name: "Corsola", number: "222", type: ["Water", "Rock"]),
//        PokemonTypes(name: "Remoraid", number: "223", type: ["Water"]),
//        PokemonTypes(name: "Octillery", number: "224", type: ["Water"]),
//        PokemonTypes(name: "Delibird", number: "225", type: ["Ice", "Flying"]),
//        PokemonTypes(name: "Mantine", number: "226", type: ["Water", "Flying"]),
//        PokemonTypes(name: "Skarmory", number: "227", type: ["Steel", "Flying"]),
//        PokemonTypes(name: "Houndour", number: "228", type: ["Dark", "Fire"]),
//        PokemonTypes(name: "Houndoom", number: "229", type: ["Dark", "Fire"]),
//        PokemonTypes(name: "Kingdra", number: "230", type: ["Water", "Dragon"]),
//        PokemonTypes(name: "Phanpy", number: "231", type: ["Ground"]),
//        PokemonTypes(name: "Donphan", number: "232", type: ["Ground"]),
//        PokemonTypes(name: "Porygon2", number: "233", type: ["Normal"]),
//        PokemonTypes(name: "Stantler", number: "234", type: ["Normal"]),
//        PokemonTypes(name: "Smeargle", number: "235", type: ["Normal"]),
//        PokemonTypes(name: "Tyrogue", number: "236", type: ["Fighting"]),
//        PokemonTypes(name: "Hitmontop", number: "237", type: ["Fighting"]),
//        PokemonTypes(name: "Smoochum", number: "238", type: ["Ice", "Psychic"]),
//        PokemonTypes(name: "Elekid", number: "239", type: ["Electric"]),
//        PokemonTypes(name: "Magby", number: "240", type: ["Fire"]),
//        PokemonTypes(name: "Miltank", number: "241", type: ["Normal"]),
//        PokemonTypes(name: "Blissey", number: "242", type: ["Normal"]),
//        PokemonTypes(name: "Raikou", number: "243", type: ["Electric"]),
//        PokemonTypes(name: "Entei", number: "244", type: ["Fire"]),
//        PokemonTypes(name: "Suicune", number: "245", type: ["Water"]),
//        PokemonTypes(name: "Larvitar", number: "246", type: ["Rock", "Ground"]),
//        PokemonTypes(name: "Pupitar", number: "247", type: ["Rock", "Ground"]),
//        PokemonTypes(name: "Tyranitar", number: "248", type: ["Rock", "Dark"]),
//        PokemonTypes(name: "Lugia", number: "249", type: ["Psychic", "Flying"]),
//        PokemonTypes(name: "Ho-Oh", number: "250", type: ["Fire", "Flying"]),
//        PokemonTypes(name: "Celebi", number: "251", type: ["Psychic", "Grass"]),
//        PokemonTypes(name: "Treecko", number: "252", type: ["Grass"]),
//        PokemonTypes(name: "Grovyle", number: "253", type: ["Grass"]),
//        PokemonTypes(name: "Sceptile", number: "254", type: ["Grass"]),
//        PokemonTypes(name: "Torchic", number: "255", type: ["Fire"]),
//        PokemonTypes(name: "Combusken", number: "256", type: ["Fire", "Fighting"]),
//        PokemonTypes(name: "Blaziken", number: "257", type: ["Fire", "Fighting"]),
//        PokemonTypes(name: "Mudkip", number: "258", type: ["Water"]),
//        PokemonTypes(name: "Marshtomp", number: "259", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Swampert", number: "260", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Poochyena", number: "261", type: ["Dark"]),
//        PokemonTypes(name: "Mightyena", number: "262", type: ["Dark"]),
//        PokemonTypes(name: "Zigzagoon", number: "263", type: ["Normal"]),
//        PokemonTypes(name: "Linoone", number: "264", type: ["Normal"]),
//        PokemonTypes(name: "Wurmple", number: "265", type: ["Bug"]),
//        PokemonTypes(name: "Silcoon", number: "266", type: ["Bug"]),
//        PokemonTypes(name: "Beautifly", number: "267", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Cascoon", number: "268", type: ["Bug"]),
//        PokemonTypes(name: "Dustox", number: "269", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Lotad", number: "270", type: ["Water", "Grass"]),
//        PokemonTypes(name: "Lombre", number: "271", type: ["Water", "Grass"]),
//        PokemonTypes(name: "Ludicolo", number: "272", type: ["Water", "Grass"]),
//        PokemonTypes(name: "Seedot", number: "273", type: ["Grass"]),
//        PokemonTypes(name: "Nuzleaf", number: "274", type: ["Grass", "Dark"]),
//        PokemonTypes(name: "Shiftry", number: "275", type: ["Grass", "Dark"]),
//        PokemonTypes(name: "Taillow", number: "276", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Swellow", number: "277", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Wingull", number: "278", type: ["Water", "Flying"]),
//        PokemonTypes(name: "Pelipper", number: "279", type: ["Water", "Flying"]),
//        PokemonTypes(name: "Ralts", number: "280", type: ["Psychic", "Fairy"]),
//        PokemonTypes(name: "Kirlia", number: "281", type: ["Psychic", "Fairy"]),
//        PokemonTypes(name: "Gardevoir", number: "282", type: ["Psychic", "Fairy"]),
//        PokemonTypes(name: "Surskit", number: "283", type: ["Bug", "Water"]),
//        PokemonTypes(name: "Masquerain", number: "284", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Shroomish", number: "285", type: ["Grass"]),
//        PokemonTypes(name: "Breloom", number: "286", type: ["Grass", "Fighting"]),
//        PokemonTypes(name: "Slakoth", number: "287", type: ["Normal"]),
//        PokemonTypes(name: "Vigoroth", number: "288", type: ["Normal"]),
//        PokemonTypes(name: "Slaking", number: "289", type: ["Normal"]),
//        PokemonTypes(name: "Nincada", number: "290", type: ["Bug", "Ground"]),
//        PokemonTypes(name: "Ninjask", number: "291", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Shedinja", number: "292", type: ["Bug", "Ghost"]),
//        PokemonTypes(name: "Whismur", number: "293", type: ["Normal"]),
//        PokemonTypes(name: "Loudred", number: "294", type: ["Normal"]),
//        PokemonTypes(name: "Exploud", number: "295", type: ["Normal"]),
//        PokemonTypes(name: "Makuhita", number: "296", type: ["Fighting"]),
//        PokemonTypes(name: "Hariyama", number: "297", type: ["Fighting"]),
//        PokemonTypes(name: "Azurill", number: "298", type: ["Normal", "Fairy"]),
//        PokemonTypes(name: "Nosepass", number: "299", type: ["Rock"]),
//        PokemonTypes(name: "Skitty", number: "300", type: ["Normal"]),
//        PokemonTypes(name: "Delcatty", number: "301", type: ["Normal"]),
//        PokemonTypes(name: "Sableye", number: "302", type: ["Dark", "Ghost"]),
//        PokemonTypes(name: "Mawile", number: "303", type: ["Steel", "Fairy"]),
//        PokemonTypes(name: "Aron", number: "304", type: ["Steel", "Rock"]),
//        PokemonTypes(name: "Lairon", number: "305", type: ["Steel", "Rock"]),
//        PokemonTypes(name: "Aggron", number: "306", type: ["Steel", "Rock"]),
//        PokemonTypes(name: "Meditite", number: "307", type: ["Fighting", "Psychic"]),
//        PokemonTypes(name: "Medicham", number: "308", type: ["Fighting", "Psychic"]),
//        PokemonTypes(name: "Electrike", number: "309", type: ["Electric"]),
//        PokemonTypes(name: "Manectric", number: "310", type: ["Electric"]),
//        PokemonTypes(name: "Plusle", number: "311", type: ["Electric"]),
//        PokemonTypes(name: "Minun", number: "312", type: ["Electric"]),
//        PokemonTypes(name: "Volbeat", number: "313", type: ["Bug"]),
//        PokemonTypes(name: "Illumise", number: "314", type: ["Bug"]),
//        PokemonTypes(name: "Roselia", number: "315", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Gulpin", number: "316", type: ["Poison"]),
//        PokemonTypes(name: "Swalot", number: "317", type: ["Poison"]),
//        PokemonTypes(name: "Carvanha", number: "318", type: ["Water", "Dark"]),
//        PokemonTypes(name: "Sharpedo", number: "319", type: ["Water", "Dark"]),
//        PokemonTypes(name: "Wailmer", number: "320", type: ["Water"]),
//        PokemonTypes(name: "Wailord", number: "321", type: ["Water"]),
//        PokemonTypes(name: "Numel", number: "322", type: ["Fire", "Ground"]),
//        PokemonTypes(name: "Camerupt", number: "323", type: ["Fire", "Ground"]),
//        PokemonTypes(name: "Torkoal", number: "324", type: ["Fire"]),
//        PokemonTypes(name: "Spoink", number: "325", type: ["Psychic"]),
//        PokemonTypes(name: "Grumpig", number: "326", type: ["Psychic"]),
//        PokemonTypes(name: "Spinda", number: "327", type: ["Normal"]),
//        PokemonTypes(name: "Trapinch", number: "328", type: ["Ground"]),
//        PokemonTypes(name: "Vibrava", number: "329", type: ["Ground", "Dragon"]),
//        PokemonTypes(name: "Flygon", number: "330", type: ["Ground", "Dragon"]),
//        PokemonTypes(name: "Cacnea", number: "331", type: ["Grass"]),
//        PokemonTypes(name: "Cacturne", number: "332", type: ["Grass", "Dark"]),
//        PokemonTypes(name: "Swablu", number: "333", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Altaria", number: "334", type: ["Dragon", "Flying"]),
//        PokemonTypes(name: "Zangoose", number: "335", type: ["Normal"]),
//        PokemonTypes(name: "Seviper", number: "336", type: ["Poison"]),
//        PokemonTypes(name: "Lunatone", number: "337", type: ["Rock", "Psychic"]),
//        PokemonTypes(name: "Solrock", number: "338", type: ["Rock", "Psychic"]),
//        PokemonTypes(name: "Barboach", number: "339", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Whiscash", number: "340", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Corphish", number: "341", type: ["Water"]),
//        PokemonTypes(name: "Crawdaunt", number: "342", type: ["Water", "Dark"]),
//        PokemonTypes(name: "Baltoy", number: "343", type: ["Ground", "Psychic"]),
//        PokemonTypes(name: "Claydol", number: "344", type: ["Ground", "Psychic"]),
//        PokemonTypes(name: "Lileep", number: "345", type: ["Rock", "Grass"]),
//        PokemonTypes(name: "Cradily", number: "346", type: ["Rock", "Grass"]),
//        PokemonTypes(name: "Anorith", number: "347", type: ["Rock", "Bug"]),
//        PokemonTypes(name: "Armaldo", number: "348", type: ["Rock", "Bug"]),
//        PokemonTypes(name: "Feebas", number: "349", type: ["Water"]),
//        PokemonTypes(name: "Milotic", number: "350", type: ["Water"]),
//        PokemonTypes(name: "Castform", number: "351", type: ["Normal"]),
//        PokemonTypes(name: "Kecleon", number: "352", type: ["Normal"]),
//        PokemonTypes(name: "Shuppet", number: "353", type: ["Ghost"]),
//        PokemonTypes(name: "Banette", number: "354", type: ["Ghost"]),
//        PokemonTypes(name: "Duskull", number: "355", type: ["Ghost"]),
//        PokemonTypes(name: "Dusclops", number: "356", type: ["Ghost"]),
//        PokemonTypes(name: "Tropius", number: "357", type: ["Grass", "Flying"]),
//        PokemonTypes(name: "Chimecho", number: "358", type: ["Psychic"]),
//        PokemonTypes(name: "Absol", number: "359", type: ["Dark"]),
//        PokemonTypes(name: "Wynaut", number: "360", type: ["Psychic"]),
//        PokemonTypes(name: "Snorunt", number: "361", type: ["Ice"]),
//        PokemonTypes(name: "Glalie", number: "362", type: ["Ice"]),
//        PokemonTypes(name: "Spheal", number: "363", type: ["Ice", "Water"]),
//        PokemonTypes(name: "Sealeo", number: "364", type: ["Ice", "Water"]),
//        PokemonTypes(name: "Walrein", number: "365", type: ["Ice", "Water"]),
//        PokemonTypes(name: "Clamperl", number: "366", type: ["Water"]),
//        PokemonTypes(name: "Huntail", number: "367", type: ["Water"]),
//        PokemonTypes(name: "Gorebyss", number: "368", type: ["Water"]),
//        PokemonTypes(name: "Relicanth", number: "369", type: ["Water", "Rock"]),
//        PokemonTypes(name: "Luvdisc", number: "370", type: ["Water"]),
//        PokemonTypes(name: "Bagon", number: "371", type: ["Dragon"]),
//        PokemonTypes(name: "Shelgon", number: "372", type: ["Dragon"]),
//        PokemonTypes(name: "Salamence", number: "373", type: ["Dragon", "Flying"]),
//        PokemonTypes(name: "Beldum", number: "374", type: ["Steel", "Psychic"]),
//        PokemonTypes(name: "Metang", number: "375", type: ["Steel", "Psychic"]),
//        PokemonTypes(name: "Metagross", number: "376", type: ["Steel", "Psychic"]),
//        PokemonTypes(name: "Regirock", number: "377", type: ["Rock"]),
//        PokemonTypes(name: "Regice", number: "378", type: ["Ice"]),
//        PokemonTypes(name: "Registeel", number: "379", type: ["Steel"]),
//        PokemonTypes(name: "Latias", number: "380", type: ["Dragon", "Psychic"]),
//        PokemonTypes(name: "Latios", number: "381", type: ["Dragon", "Psychic"]),
//        PokemonTypes(name: "Kyogre", number: "382", type: ["Water"]),
//        PokemonTypes(name: "Groudon", number: "383", type: ["Ground"]),
//        PokemonTypes(name: "Rayquaza", number: "384", type: ["Dragon", "Flying"]),
//        PokemonTypes(name: "Jirachi", number: "385", type: ["Steel", "Psychic"]),
//        PokemonTypes(name: "Deoxys", number: "386", type: ["Psychic"]),
//        PokemonTypes(name: "Turtwig", number: "387", type: ["Grass"]),
//        PokemonTypes(name: "Grotle", number: "388", type: ["Grass"]),
//        PokemonTypes(name: "Torterra", number: "389", type: ["Grass", "Ground"]),
//        PokemonTypes(name: "Chimchar", number: "390", type: ["Fire"]),
//        PokemonTypes(name: "Monferno", number: "391", type: ["Fire", "Fighting"]),
//        PokemonTypes(name: "Infernape", number: "392", type: ["Fire", "Fighting"]),
//        PokemonTypes(name: "Piplup", number: "393", type: ["Water"]),
//        PokemonTypes(name: "Prinplup", number: "394", type: ["Water"]),
//        PokemonTypes(name: "Empoleon", number: "395", type: ["Water", "Steel"]),
//        PokemonTypes(name: "Starly", number: "396", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Staravia", number: "397", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Staraptor", number: "398", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Bidoof", number: "399", type: ["Normal"]),
//        PokemonTypes(name: "Bibarel", number: "400", type: ["Normal", "Water"]),
//        PokemonTypes(name: "Kricketot", number: "401", type: ["Bug"]),
//        PokemonTypes(name: "Kricketune", number: "402", type: ["Bug"]),
//        PokemonTypes(name: "Shinx", number: "403", type: ["Electric"]),
//        PokemonTypes(name: "Luxio", number: "404", type: ["Electric"]),
//        PokemonTypes(name: "Luxray", number: "405", type: ["Electric"]),
//        PokemonTypes(name: "Budew", number: "406", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Roserade", number: "407", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Cranidos", number: "408", type: ["Rock"]),
//        PokemonTypes(name: "Rampardos", number: "409", type: ["Rock"]),
//        PokemonTypes(name: "Shieldon", number: "410", type: ["Rock", "Steel"]),
//        PokemonTypes(name: "Bastiodon", number: "411", type: ["Rock", "Steel"]),
//        PokemonTypes(name: "Burmy", number: "412", type: ["Bug"]),
//        PokemonTypes(name: "Wormadam", number: "413", type: ["Bug", "Grass"]),
//        PokemonTypes(name: "Mothim", number: "414", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Combee", number: "415", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Vespiquen", number: "416", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Pachirisu", number: "417", type: ["Electric"]),
//        PokemonTypes(name: "Buizel", number: "418", type: ["Water"]),
//        PokemonTypes(name: "Floatzel", number: "419", type: ["Water"]),
//        PokemonTypes(name: "Cherubi", number: "420", type: ["Grass"]),
//        PokemonTypes(name: "Cherrim", number: "421", type: ["Grass"]),
//        PokemonTypes(name: "Shellos", number: "422", type: ["Water"]),
//        PokemonTypes(name: "Gastrodon", number: "423", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Ambipom", number: "424", type: ["Normal"]),
//        PokemonTypes(name: "Drifloon", number: "425", type: ["Ghost", "Flying"]),
//        PokemonTypes(name: "Drifblim", number: "426", type: ["Ghost", "Flying"]),
//        PokemonTypes(name: "Buneary", number: "427", type: ["Normal"]),
//        PokemonTypes(name: "Lopunny", number: "428", type: ["Normal"]),
//        PokemonTypes(name: "Mismagius", number: "429", type: ["Ghost"]),
//        PokemonTypes(name: "Honchkrow", number: "430", type: ["Dark", "Flying"]),
//        PokemonTypes(name: "Glameow", number: "431", type: ["Normal"]),
//        PokemonTypes(name: "Purugly", number: "432", type: ["Normal"]),
//        PokemonTypes(name: "Chingling", number: "433", type: ["Psychic"]),
//        PokemonTypes(name: "Stunky", number: "434", type: ["Poison", "Dark"]),
//        PokemonTypes(name: "Skuntank", number: "435", type: ["Poison", "Dark"]),
//        PokemonTypes(name: "Bronzor", number: "436", type: ["Steel", "Psychic"]),
//        PokemonTypes(name: "Bronzong", number: "437", type: ["Steel", "Psychic"]),
//        PokemonTypes(name: "Bonsly", number: "438", type: ["Rock"]),
//        PokemonTypes(name: "Mime Jr.", number: "439", type: ["Psychic", "Fairy"]),
//        PokemonTypes(name: "Happiny", number: "440", type: ["Normal"]),
//        PokemonTypes(name: "Chatot", number: "441", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Spiritomb", number: "442", type: ["Ghost", "Dark"]),
//        PokemonTypes(name: "Gible", number: "443", type: ["Dragon", "Ground"]),
//        PokemonTypes(name: "Gabite", number: "444", type: ["Dragon", "Ground"]),
//        PokemonTypes(name: "Garchomp", number: "445", type: ["Dragon", "Ground"]),
//        PokemonTypes(name: "Munchlax", number: "446", type: ["Normal"]),
//        PokemonTypes(name: "Riolu", number: "447", type: ["Fighting"]),
//        PokemonTypes(name: "Lucario", number: "448", type: ["Fighting", "Steel"]),
//        PokemonTypes(name: "Hippopotas", number: "449", type: ["Ground"]),
//        PokemonTypes(name: "Hippowdon", number: "450", type: ["Ground"]),
//        PokemonTypes(name: "Skorupi", number: "451", type: ["Poison", "Bug"]),
//        PokemonTypes(name: "Drapion", number: "452", type: ["Poison", "Dark"]),
//        PokemonTypes(name: "Croagunk", number: "453", type: ["Poison", "Fighting"]),
//        PokemonTypes(name: "Toxicroak", number: "454", type: ["Poison", "Fighting"]),
//        PokemonTypes(name: "Carnivine", number: "455", type: ["Grass"]),
//        PokemonTypes(name: "Finneon", number: "456", type: ["Water"]),
//        PokemonTypes(name: "Lumineon", number: "457", type: ["Water"]),
//        PokemonTypes(name: "Mantyke", number: "458", type: ["Water", "Flying"]),
//        PokemonTypes(name: "Snover", number: "459", type: ["Grass", "Ice"]),
//        PokemonTypes(name: "Abomasnow", number: "460", type: ["Grass", "Ice"]),
//        PokemonTypes(name: "Weavile", number: "461", type: ["Dark", "Ice"]),
//        PokemonTypes(name: "Magnezone", number: "462", type: ["Electric", "Steel"]),
//        PokemonTypes(name: "Lickilicky", number: "463", type: ["Normal"]),
//        PokemonTypes(name: "Rhyperior", number: "464", type: ["Ground", "Rock"]),
//        PokemonTypes(name: "Tangrowth", number: "465", type: ["Grass"]),
//        PokemonTypes(name: "Electivire", number: "466", type: ["Electric"]),
//        PokemonTypes(name: "Magmortar", number: "467", type: ["Fire"]),
//        PokemonTypes(name: "Togekiss", number: "468", type: ["Fairy", "Flying"]),
//        PokemonTypes(name: "Yanmega", number: "469", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Leafeon", number: "470", type: ["Grass"]),
//        PokemonTypes(name: "Glaceon", number: "471", type: ["Ice"]),
//        PokemonTypes(name: "Gliscor", number: "472", type: ["Ground", "Flying"]),
//        PokemonTypes(name: "Mamoswine", number: "473", type: ["Ice", "Ground"]),
//        PokemonTypes(name: "Porygon-Z", number: "474", type: ["Normal"]),
//        PokemonTypes(name: "Gallade", number: "475", type: ["Psychic", "Fighting"]),
//        PokemonTypes(name: "Probopass", number: "476", type: ["Rock", "Steel"]),
//        PokemonTypes(name: "Dusknoir", number: "477", type: ["Ghost"]),
//        PokemonTypes(name: "Froslass", number: "478", type: ["Ice", "Ghost"]),
//        PokemonTypes(name: "Rotom", number: "479", type: ["Electric", "Ghost"]),
//        PokemonTypes(name: "Uxie", number: "480", type: ["Psychic"]),
//        PokemonTypes(name: "Mesprit", number: "481", type: ["Psychic"]),
//        PokemonTypes(name: "Azelf", number: "482", type: ["Psychic"]),
//        PokemonTypes(name: "Dialga", number: "483", type: ["Steel", "Dragon"]),
//        PokemonTypes(name: "Palkia", number: "484", type: ["Water", "Dragon"]),
//        PokemonTypes(name: "Heatran", number: "485", type: ["Fire", "Steel"]),
//        PokemonTypes(name: "Regigigas", number: "486", type: ["Normal"]),
//        PokemonTypes(name: "Giratina", number: "487", type: ["Ghost", "Dragon"]),
//        PokemonTypes(name: "Cresselia", number: "488", type: ["Psychic"]),
//        PokemonTypes(name: "Phione", number: "489", type: ["Water"]),
//        PokemonTypes(name: "Manaphy", number: "490", type: ["Water"]),
//        PokemonTypes(name: "Darkrai", number: "491", type: ["Dark"]),
//        PokemonTypes(name: "Shaymin", number: "492", type: ["Grass"]),
//        PokemonTypes(name: "Arceus", number: "493", type: ["Normal"]),
//        PokemonTypes(name: "Victini", number: "494", type: ["Psychic", "Fire"]),
//        PokemonTypes(name: "Snivy", number: "495", type: ["Grass"]),
//        PokemonTypes(name: "Servine", number: "496", type: ["Grass"]),
//        PokemonTypes(name: "Serperior", number: "497", type: ["Grass"]),
//        PokemonTypes(name: "Tepig", number: "498", type: ["Fire"]),
//        PokemonTypes(name: "Pignite", number: "499", type: ["Fire", "Fighting"]),
//        PokemonTypes(name: "Emboar", number: "500", type: ["Fire", "Fighting"]),
//        PokemonTypes(name: "Oshawott", number: "501", type: ["Water"]),
//        PokemonTypes(name: "Dewott", number: "502", type: ["Water"]),
//        PokemonTypes(name: "Samurott", number: "503", type: ["Water"]),
//        PokemonTypes(name: "Patrat", number: "504", type: ["Normal"]),
//        PokemonTypes(name: "Watchog", number: "505", type: ["Normal"]),
//        PokemonTypes(name: "Lillipup", number: "506", type: ["Normal"]),
//        PokemonTypes(name: "Herdier", number: "507", type: ["Normal"]),
//        PokemonTypes(name: "Stoutland", number: "508", type: ["Normal"]),
//        PokemonTypes(name: "Purrloin", number: "509", type: ["Dark"]),
//        PokemonTypes(name: "Liepard", number: "510", type: ["Dark"]),
//        PokemonTypes(name: "Pansage", number: "511", type: ["Grass"]),
//        PokemonTypes(name: "Simisage", number: "512", type: ["Grass"]),
//        PokemonTypes(name: "Pansear", number: "513", type: ["Fire"]),
//        PokemonTypes(name: "Simisear", number: "514", type: ["Fire"]),
//        PokemonTypes(name: "Panpour", number: "515", type: ["Water"]),
//        PokemonTypes(name: "Simipour", number: "516", type: ["Water"]),
//        PokemonTypes(name: "Munna", number: "517", type: ["Psychic"]),
//        PokemonTypes(name: "Musharna", number: "518", type: ["Psychic"]),
//        PokemonTypes(name: "Pidove", number: "519", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Tranquill", number: "520", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Unfezant", number: "521", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Blitzle", number: "522", type: ["Electric"]),
//        PokemonTypes(name: "Zebstrika", number: "523", type: ["Electric"]),
//        PokemonTypes(name: "Roggenrola", number: "524", type: ["Rock"]),
//        PokemonTypes(name: "Boldore", number: "525", type: ["Rock"]),
//        PokemonTypes(name: "Gigalith", number: "526", type: ["Rock"]),
//        PokemonTypes(name: "Woobat", number: "527", type: ["Psychic", "Flying"]),
//        PokemonTypes(name: "Swoobat", number: "528", type: ["Psychic", "Flying"]),
//        PokemonTypes(name: "Drilbur", number: "529", type: ["Ground"]),
//        PokemonTypes(name: "Excadrill", number: "530", type: ["Ground", "Steel"]),
//        PokemonTypes(name: "Audino", number: "531", type: ["Normal"]),
//        PokemonTypes(name: "Timburr", number: "532", type: ["Fighting"]),
//        PokemonTypes(name: "Gurdurr", number: "533", type: ["Fighting"]),
//        PokemonTypes(name: "Conkeldurr", number: "534", type: ["Fighting"]),
//        PokemonTypes(name: "Tympole", number: "535", type: ["Water"]),
//        PokemonTypes(name: "Palpitoad", number: "536", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Seismitoad", number: "537", type: ["Water", "Ground"]),
//        PokemonTypes(name: "Throh", number: "538", type: ["Fighting"]),
//        PokemonTypes(name: "Sawk", number: "539", type: ["Fighting"]),
//        PokemonTypes(name: "Sewaddle", number: "540", type: ["Bug", "Grass"]),
//        PokemonTypes(name: "Swadloon", number: "541", type: ["Bug", "Grass"]),
//        PokemonTypes(name: "Leavanny", number: "542", type: ["Bug", "Grass"]),
//        PokemonTypes(name: "Venipede", number: "543", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Whirlipede", number: "544", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Scolipede", number: "545", type: ["Bug", "Poison"]),
//        PokemonTypes(name: "Cottonee", number: "546", type: ["Grass", "Fairy"]),
//        PokemonTypes(name: "Whimsicott", number: "547", type: ["Grass", "Fairy"]),
//        PokemonTypes(name: "Petilil", number: "548", type: ["Grass"]),
//        PokemonTypes(name: "Lilligant", number: "549", type: ["Grass"]),
//        PokemonTypes(name: "Basculin", number: "550", type: ["Water"]),
//        PokemonTypes(name: "Sandile", number: "551", type: ["Ground", "Dark"]),
//        PokemonTypes(name: "Krokorok", number: "552", type: ["Ground", "Dark"]),
//        PokemonTypes(name: "Krookodile", number: "553", type: ["Ground", "Dark"]),
//        PokemonTypes(name: "Darumaka", number: "554", type: ["Fire"]),
//        PokemonTypes(name: "Darmanitan", number: "555", type: ["Fire"]),
//        PokemonTypes(name: "Maractus", number: "556", type: ["Grass"]),
//        PokemonTypes(name: "Dwebble", number: "557", type: ["Bug", "Rock"]),
//        PokemonTypes(name: "Crustle", number: "558", type: ["Bug", "Rock"]),
//        PokemonTypes(name: "Scraggy", number: "559", type: ["Dark", "Fighting"]),
//        PokemonTypes(name: "Scrafty", number: "560", type: ["Dark", "Fighting"]),
//        PokemonTypes(name: "Sigilyph", number: "561", type: ["Psychic", "Flying"]),
//        PokemonTypes(name: "Yamask", number: "562", type: ["Ghost"]),
//        PokemonTypes(name: "Cofagrigus", number: "563", type: ["Ghost"]),
//        PokemonTypes(name: "Tirtouga", number: "564", type: ["Water", "Rock"]),
//        PokemonTypes(name: "Carracosta", number: "565", type: ["Water", "Rock"]),
//        PokemonTypes(name: "Archen", number: "566", type: ["Rock", "Flying"]),
//        PokemonTypes(name: "Archeops", number: "567", type: ["Rock", "Flying"]),
//        PokemonTypes(name: "Trubbish", number: "568", type: ["Poison"]),
//        PokemonTypes(name: "Garbodor", number: "569", type: ["Poison"]),
//        PokemonTypes(name: "Zorua", number: "570", type: ["Dark"]),
//        PokemonTypes(name: "Zoroark", number: "571", type: ["Dark"]),
//        PokemonTypes(name: "Minccino", number: "572", type: ["Normal"]),
//        PokemonTypes(name: "Cinccino", number: "573", type: ["Normal"]),
//        PokemonTypes(name: "Gothita", number: "574", type: ["Psychic"]),
//        PokemonTypes(name: "Gothorita", number: "575", type: ["Psychic"]),
//        PokemonTypes(name: "Gothitelle", number: "576", type: ["Psychic"]),
//        PokemonTypes(name: "Solosis", number: "577", type: ["Psychic"]),
//        PokemonTypes(name: "Duosion", number: "578", type: ["Psychic"]),
//        PokemonTypes(name: "Reuniclus", number: "579", type: ["Psychic"]),
//        PokemonTypes(name: "Ducklett", number: "580", type: ["Water", "Flying"]),
//        PokemonTypes(name: "Swanna", number: "581", type: ["Water", "Flying"]),
//        PokemonTypes(name: "Vanillite", number: "582", type: ["Ice"]),
//        PokemonTypes(name: "Vanillish", number: "583", type: ["Ice"]),
//        PokemonTypes(name: "Vanilluxe", number: "584", type: ["Ice"]),
//        PokemonTypes(name: "Deerling", number: "585", type: ["Normal", "Grass"]),
//        PokemonTypes(name: "Sawsbuck", number: "586", type: ["Normal", "Grass"]),
//        PokemonTypes(name: "Emolga", number: "587", type: ["Electric", "Flying"]),
//        PokemonTypes(name: "Karrablast", number: "588", type: ["Bug"]),
//        PokemonTypes(name: "Escavalier", number: "589", type: ["Bug", "Steel"]),
//        PokemonTypes(name: "Foongus", number: "590", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Amoonguss", number: "591", type: ["Grass", "Poison"]),
//        PokemonTypes(name: "Frillish", number: "592", type: ["Water", "Ghost"]),
//        PokemonTypes(name: "Jellicent", number: "593", type: ["Water", "Ghost"]),
//        PokemonTypes(name: "Alomomola", number: "594", type: ["Water"]),
//        PokemonTypes(name: "Joltik", number: "595", type: ["Bug", "Electric"]),
//        PokemonTypes(name: "Galvantula", number: "596", type: ["Bug", "Electric"]),
//        PokemonTypes(name: "Ferroseed", number: "597", type: ["Grass", "Steel"]),
//        PokemonTypes(name: "Ferrothorn", number: "598", type: ["Grass", "Steel"]),
//        PokemonTypes(name: "Klink", number: "599", type: ["Steel"]),
//        PokemonTypes(name: "Klang", number: "600", type: ["Steel"]),
//        PokemonTypes(name: "Klinklang", number: "601", type: ["Steel"]),
//        PokemonTypes(name: "Tynamo", number: "602", type: ["Electric"]),
//        PokemonTypes(name: "Eelektrik", number: "603", type: ["Electric"]),
//        PokemonTypes(name: "Eelektross", number: "604", type: ["Electric"]),
//        PokemonTypes(name: "Elgyem", number: "605", type: ["Psychic"]),
//        PokemonTypes(name: "Beheeyem", number: "606", type: ["Psychic"]),
//        PokemonTypes(name: "Litwick", number: "607", type: ["Ghost", "Fire"]),
//        PokemonTypes(name: "Lampent", number: "608", type: ["Ghost", "Fire"]),
//        PokemonTypes(name: "Chandelure", number: "609", type: ["Ghost", "Fire"]),
//        PokemonTypes(name: "Axew", number: "610", type: ["Dragon"]),
//        PokemonTypes(name: "Fraxure", number: "611", type: ["Dragon"]),
//        PokemonTypes(name: "Haxorus", number: "612", type: ["Dragon"]),
//        PokemonTypes(name: "Cubchoo", number: "613", type: ["Ice"]),
//        PokemonTypes(name: "Beartic", number: "614", type: ["Ice"]),
//        PokemonTypes(name: "Cryogonal", number: "615", type: ["Ice"]),
//        PokemonTypes(name: "Shelmet", number: "616", type: ["Bug"]),
//        PokemonTypes(name: "Accelgor", number: "617", type: ["Bug"]),
//        PokemonTypes(name: "Stunfisk", number: "618", type: ["Ground", "Electric"]),
//        PokemonTypes(name: "Mienfoo", number: "619", type: ["Fighting"]),
//        PokemonTypes(name: "Mienshao", number: "620", type: ["Fighting"]),
//        PokemonTypes(name: "Druddigon", number: "621", type: ["Dragon"]),
//        PokemonTypes(name: "Golett", number: "622", type: ["Ground", "Ghost"]),
//        PokemonTypes(name: "Golurk", number: "623", type: ["Ground", "Ghost"]),
//        PokemonTypes(name: "Pawniard", number: "624", type: ["Dark", "Steel"]),
//        PokemonTypes(name: "Bisharp", number: "625", type: ["Dark", "Steel"]),
//        PokemonTypes(name: "Bouffalant", number: "626", type: ["Normal"]),
//        PokemonTypes(name: "Rufflet", number: "627", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Braviary", number: "628", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Vullaby", number: "629", type: ["Dark", "Flying"]),
//        PokemonTypes(name: "Mandibuzz", number: "630", type: ["Dark", "Flying"]),
//        PokemonTypes(name: "Heatmor", number: "631", type: ["Fire"]),
//        PokemonTypes(name: "Durant", number: "632", type: ["Bug", "Steel"]),
//        PokemonTypes(name: "Deino", number: "633", type: ["Dark", "Dragon"]),
//        PokemonTypes(name: "Zweilous", number: "634", type: ["Dark", "Dragon"]),
//        PokemonTypes(name: "Hydreigon", number: "635", type: ["Dark", "Dragon"]),
//        PokemonTypes(name: "Larvesta", number: "636", type: ["Bug", "Fire"]),
//        PokemonTypes(name: "Volcarona", number: "637", type: ["Bug", "Fire"]),
//        PokemonTypes(name: "Cobalion", number: "638", type: ["Steel", "Fighting"]),
//        PokemonTypes(name: "Terrakion", number: "639", type: ["Rock", "Fighting"]),
//        PokemonTypes(name: "Virizion", number: "640", type: ["Grass", "Fighting"]),
//        PokemonTypes(name: "Tornadus", number: "641", type: ["Flying"]),
//        PokemonTypes(name: "Thundurus", number: "642", type: ["Electric", "Flying"]),
//        PokemonTypes(name: "Reshiram", number: "643", type: ["Dragon", "Fire"]),
//        PokemonTypes(name: "Zekrom", number: "644", type: ["Dragon", "Electric"]),
//        PokemonTypes(name: "Landorus", number: "645", type: ["Ground", "Flying"]),
//        PokemonTypes(name: "Kyurem", number: "646", type: ["Dragon", "Ice"]),
//        PokemonTypes(name: "Keldeo", number: "647", type: ["Water", "Fighting"]),
//        PokemonTypes(name: "Meloetta", number: "648", type: ["Normal", "Psychic"]),
//        PokemonTypes(name: "Genesect", number: "649", type: ["Bug", "Steel"]),
//        PokemonTypes(name: "Chespin", number: "650", type: ["Grass"]),
//        PokemonTypes(name: "Quilladin", number: "651", type: ["Grass"]),
//        PokemonTypes(name: "Chesnaught", number: "652", type: ["Grass", "Fighting"]),
//        PokemonTypes(name: "Fennekin", number: "653", type: ["Fire"]),
//        PokemonTypes(name: "Braixen", number: "654", type: ["Fire"]),
//        PokemonTypes(name: "Delphox", number: "655", type: ["Fire", "Psychic"]),
//        PokemonTypes(name: "Froakie", number: "656", type: ["Water"]),
//        PokemonTypes(name: "Frogadier", number: "657", type: ["Water"]),
//        PokemonTypes(name: "Greninja", number: "658", type: ["Water", "Dark"]),
//        PokemonTypes(name: "Bunnelby", number: "659", type: ["Normal"]),
//        PokemonTypes(name: "Diggersby", number: "660", type: ["Normal", "Ground"]),
//        PokemonTypes(name: "Fletchling", number: "661", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Fletchinder", number: "662", type: ["Fire", "Flying"]),
//        PokemonTypes(name: "Talonflame", number: "663", type: ["Fire", "Flying"]),
//        PokemonTypes(name: "Scatterbug", number: "664", type: ["Bug"]),
//        PokemonTypes(name: "Spewpa", number: "665", type: ["Bug"]),
//        PokemonTypes(name: "Vivillon", number: "666", type: ["Bug", "Flying"]),
//        PokemonTypes(name: "Litleo", number: "667", type: ["Fire", "Normal"]),
//        PokemonTypes(name: "Pyroar", number: "668", type: ["Fire", "Normal"]),
//        PokemonTypes(name: "Flabébé", number: "669", type: ["Fairy"]),
//        PokemonTypes(name: "Floette", number: "670", type: ["Fairy"]),
//        PokemonTypes(name: "Florges", number: "671", type: ["Fairy"]),
//        PokemonTypes(name: "Skiddo", number: "672", type: ["Grass"]),
//        PokemonTypes(name: "Gogoat", number: "673", type: ["Grass"]),
//        PokemonTypes(name: "Pancham", number: "674", type: ["Fighting"]),
//        PokemonTypes(name: "Pangoro", number: "675", type: ["Fighting", "Dark"]),
//        PokemonTypes(name: "Furfrou", number: "676", type: ["Normal"]),
//        PokemonTypes(name: "Espurr", number: "677", type: ["Psychic"]),
//        PokemonTypes(name: "Meowstic", number: "678", type: ["Psychic"]),
//        PokemonTypes(name: "Honedge", number: "679", type: ["Steel", "Ghost"]),
//        PokemonTypes(name: "Doublade", number: "680", type: ["Steel", "Ghost"]),
//        PokemonTypes(name: "Aegislash", number: "681", type: ["Steel", "Ghost"]),
//        PokemonTypes(name: "Spritzee", number: "682", type: ["Fairy"]),
//        PokemonTypes(name: "Aromatisse", number: "683", type: ["Fairy"]),
//        PokemonTypes(name: "Swirlix", number: "684", type: ["Fairy"]),
//        PokemonTypes(name: "Slurpuff", number: "685", type: ["Fairy"]),
//        PokemonTypes(name: "Inkay", number: "686", type: ["Dark", "Psychic"]),
//        PokemonTypes(name: "Malamar", number: "687", type: ["Dark", "Psychic"]),
//        PokemonTypes(name: "Binacle", number: "688", type: ["Rock", "Water"]),
//        PokemonTypes(name: "Barbaracle", number: "689", type: ["Rock", "Water"]),
//        PokemonTypes(name: "Skrelp", number: "690", type: ["Poison", "Water"]),
//        PokemonTypes(name: "Dragalge", number: "691", type: ["Poison", "Dragon"]),
//        PokemonTypes(name: "Clauncher", number: "692", type: ["Water"]),
//        PokemonTypes(name: "Clawitzer", number: "693", type: ["Water"]),
//        PokemonTypes(name: "Helioptile", number: "694", type: ["Electric", "Normal"]),
//        PokemonTypes(name: "Heliolisk", number: "695", type: ["Electric", "Normal"]),
//        PokemonTypes(name: "Tyrunt", number: "696", type: ["Rock", "Dragon"]),
//        PokemonTypes(name: "Tyrantrum", number: "697", type: ["Rock", "Dragon"]),
//        PokemonTypes(name: "Amaura", number: "698", type: ["Rock", "Ice"]),
//        PokemonTypes(name: "Aurorus", number: "699", type: ["Rock", "Ice"]),
//        PokemonTypes(name: "Sylveon", number: "700", type: ["Fairy"]),
//        PokemonTypes(name: "Hawlucha", number: "701", type: ["Fighting", "Flying"]),
//        PokemonTypes(name: "Dedenne", number: "702", type: ["Electric", "Fairy"]),
//        PokemonTypes(name: "Carbink", number: "703", type: ["Rock", "Fairy"]),
//        PokemonTypes(name: "Goomy", number: "704", type: ["Dragon"]),
//        PokemonTypes(name: "Sliggoo", number: "705", type: ["Dragon"]),
//        PokemonTypes(name: "Goodra", number: "706", type: ["Dragon"]),
//        PokemonTypes(name: "Klefki", number: "707", type: ["Steel", "Fairy"]),
//        PokemonTypes(name: "Phantump", number: "708", type: ["Ghost", "Grass"]),
//        PokemonTypes(name: "Trevenant", number: "709", type: ["Ghost", "Grass"]),
//        PokemonTypes(name: "Pumpkaboo", number: "710", type: ["Ghost", "Grass"]),
//        PokemonTypes(name: "Gourgeist", number: "711", type: ["Ghost", "Grass"]),
//        PokemonTypes(name: "Bergmite", number: "712", type: ["Ice"]),
//        PokemonTypes(name: "Avalugg", number: "713", type: ["Ice"]),
//        PokemonTypes(name: "Noibat", number: "714", type: ["Flying", "Dragon"]),
//        PokemonTypes(name: "Noivern", number: "715", type: ["Flying", "Dragon"]),
//        PokemonTypes(name: "Xerneas", number: "716", type: ["Fairy"]),
//        PokemonTypes(name: "Yveltal", number: "717", type: ["Dark", "Flying"]),
//        PokemonTypes(name: "Zygarde", number: "718", type: ["Dragon", "Ground"]),
//        PokemonTypes(name: "Diancie", number: "719", type: ["Rock", "Fairy"]),
//        PokemonTypes(name: "Hoopa", number: "720", type: ["Psychic", "Ghost"]),
//        PokemonTypes(name: "Volcanion", number: "721", type: ["Fire", "Water"]),
//        PokemonTypes(name: "Rowlet", number: "722", type: ["Grass", "Flying"]),
//        PokemonTypes(name: "Dartrix", number: "723", type: ["Grass", "Flying"]),
//        PokemonTypes(name: "Decidueye", number: "724", type: ["Grass", "Ghost"]),
//        PokemonTypes(name: "Litten", number: "725", type: ["Fire"]),
//        PokemonTypes(name: "Torracat", number: "726", type: ["Fire"]),
//        PokemonTypes(name: "Incineroar", number: "727", type: ["Fire", "Dark"]),
//        PokemonTypes(name: "Popplio", number: "728", type: ["Water"]),
//        PokemonTypes(name: "Brionne", number: "729", type: ["Water"]),
//        PokemonTypes(name: "Primarina", number: "730", type: ["Water", "Fairy"]),
//        PokemonTypes(name: "Pikipek", number: "731", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Trumbeak", number: "732", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Toucannon", number: "733", type: ["Normal", "Flying"]),
//        PokemonTypes(name: "Yungoos", number: "734", type: ["Normal"]),
//        PokemonTypes(name: "Gumshoos", number: "735", type: ["Normal"]),
//        PokemonTypes(name: "Grubbin", number: "736", type: ["Bug"]),
//        PokemonTypes(name: "Charjabug", number: "737", type: ["Bug", "Electric"]),
//        PokemonTypes(name: "Vikavolt", number: "738", type: ["Bug", "Electric"]),
//        PokemonTypes(name: "Crabrawler", number: "739", type: ["Fighting"]),
//        PokemonTypes(name: "Crabominable", number: "740", type: ["Fighting", "Ice"]),
//        PokemonTypes(name: "Oricorio", number: "741", type: ["Fire", "Flying"]),
//        PokemonTypes(name: "Cutiefly", number: "742", type: ["Bug", "Fairy"]),
//        PokemonTypes(name: "Ribombee", number: "743", type: ["Bug", "Fairy"]),
//        PokemonTypes(name: "Rockruff", number: "744", type: ["Rock"]),
//        PokemonTypes(name: "Lycanroc", number: "745", type: ["Rock"]),
//        PokemonTypes(name: "Wishiwashi", number: "746", type: ["Water"]),
//        PokemonTypes(name: "Mareanie", number: "747", type: ["Poison", "Water"]),
//        PokemonTypes(name: "Toxapex", number: "748", type: ["Poison", "Water"]),
//        PokemonTypes(name: "Mudbray", number: "749", type: ["Ground"]),
//        PokemonTypes(name: "Mudsdale", number: "750", type: ["Ground"]),
//        PokemonTypes(name: "Dewpider", number: "751", type: ["Water", "Bug"]),
//        PokemonTypes(name: "Araquanid", number: "752", type: ["Water", "Bug"]),
//        PokemonTypes(name: "Fomantis", number: "753", type: ["Grass"]),
//        PokemonTypes(name: "Lurantis", number: "754", type: ["Grass"]),
//        PokemonTypes(name: "Morelull", number: "755", type: ["Grass", "Fairy"]),
//        PokemonTypes(name: "Shiinotic", number: "756", type: ["Grass", "Fairy"]),
//        PokemonTypes(name: "Salandit", number: "757", type: ["Poison", "Fire"]),
//        PokemonTypes(name: "Salazzle", number: "758", type: ["Poison", "Fire"]),
//        PokemonTypes(name: "Stufful", number: "759", type: ["Normal", "Fighting"]),
//        PokemonTypes(name: "Bewear", number: "760", type: ["Normal", "Fighting"]),
//        PokemonTypes(name: "Bounsweet", number: "761", type: ["Grass"]),
//        PokemonTypes(name: "Steenee", number: "762", type: ["Grass"]),
//        PokemonTypes(name: "Tsareena", number: "763", type: ["Grass"]),
//        PokemonTypes(name: "Comfey", number: "764", type: ["Fairy"]),
//        PokemonTypes(name: "Oranguru", number: "765", type: ["Normal", "Psychic"]),
//        PokemonTypes(name: "Passimian", number: "766", type: ["Fighting"]),
//        PokemonTypes(name: "Wimpod", number: "767", type: ["Bug", "Water"]),
//        PokemonTypes(name: "Golisopod", number: "768", type: ["Bug", "Water"]),
//        PokemonTypes(name: "Sandygast", number: "769", type: ["Ghost", "Ground"]),
//        PokemonTypes(name: "Palossand", number: "770", type: ["Ghost", "Ground"]),
//        PokemonTypes(name: "Pyukumuku", number: "771", type: ["Water"]),
//        PokemonTypes(name: "Type: Null", number: "772", type: ["Normal"]),
//        PokemonTypes(name: "Silvally", number: "773", type: ["Normal"]),
//        PokemonTypes(name: "Minior", number: "774", type: ["Rock", "Flying"]),
//        PokemonTypes(name: "Komala", number: "775", type: ["Normal"]),
//        PokemonTypes(name: "Turtonator", number: "776", type: ["Fire", "Dragon"]),
//        PokemonTypes(name: "Togedemaru", number: "777", type: ["Electric", "Steel"]),
//        PokemonTypes(name: "Mimikyu", number: "778", type: ["Ghost", "Fairy"]),
//        PokemonTypes(name: "Bruxish", number: "779", type: ["Water", "Psychic"]),
//        PokemonTypes(name: "Drampa", number: "780", type: ["Normal", "Dragon"]),
//        PokemonTypes(name: "Dhelmise", number: "781", type: ["Ghost", "Grass"]),
//        PokemonTypes(name: "Jangmo-o", number: "782", type: ["Dragon"]),
//        PokemonTypes(name: "Hakamo-o", number: "783", type: ["Dragon", "Fighting"]),
//        PokemonTypes(name: "Kommo-o", number: "784", type: ["Dragon", "Fighting"]),
//        PokemonTypes(name: "Tapu Koko", number: "785", type: ["Electric", "Fairy"]),
//        PokemonTypes(name: "Tapu Lele", number: "786", type: ["Psychic", "Fairy"]),
//        PokemonTypes(name: "Tapu Bulu", number: "787", type: ["Grass", "Fairy"]),
//        PokemonTypes(name: "Tapu Fini", number: "788", type: ["Water", "Fairy"]),
//        PokemonTypes(name: "Cosmog", number: "789", type: ["Psychic"]),
//        PokemonTypes(name: "Cosmoem", number: "790", type: ["Psychic"]),
//        PokemonTypes(name: "Solgaleo", number: "791", type: ["Psychic", "Steel"]),
//        PokemonTypes(name: "Lunala", number: "792", type: ["Psychic", "Ghost"]),
//        PokemonTypes(name: "Nihilego", number: "793", type: ["Rock", "Poison"]),
//        PokemonTypes(name: "Buzzwole", number: "794", type: ["Bug", "Fighting"]),
//        PokemonTypes(name: "Pheromosa", number: "795", type: ["Bug", "Fighting"]),
//        PokemonTypes(name: "Xurkitree", number: "796", type: ["Electric"]),
//        PokemonTypes(name: "Celesteela", number: "797", type: ["Steel", "Flying"]),
//        PokemonTypes(name: "Kartana", number: "798", type: ["Grass", "Steel"]),
//        PokemonTypes(name: "Guzzlord", number: "799", type: ["Dark", "Dragon"]),
//        PokemonTypes(name: "Necrozma", number: "800", type: ["Psychic"]),
//        PokemonTypes(name: "Magearna", number: "801", type: ["Steel", "Fairy"]),
//        PokemonTypes(name: "Marshadow", number: "802", type: ["Fighting", "Ghost"]),
//        PokemonTypes(name: "Poipole", number: "803", type: ["Poison"]),
//        PokemonTypes(name: "Naganadel", number: "804", type: ["Poison", "Dragon"]),
//        PokemonTypes(name: "Stakataka", number: "805", type: ["Rock", "Steel"]),
//        PokemonTypes(name: "Blacephalon", number: "806", type: ["Fire", "Ghost"]),
//        PokemonTypes(name: "Zeraora", number: "807", type: ["Electric"]),
//        PokemonTypes(name: "Meltan", number: "808", type: ["Steel"]),
//        PokemonTypes(name: "Melmetal", number: "809", type: ["Steel"])
//        ]
//}
