//
//  PokemonDataModel.swift
//  PokeQuiz
//
//  Created by Tanner Garlick on 2/4/22.
//

import Foundation

struct Pokemon: Hashable {
    // must be hashable in order to be a key in a dictionary

    let name: String
    let number: String
    
    static var allPokemon = [
        
        Pokemon(name: "Bulbasaur", number: "001"),
        Pokemon(name: "Ivysaur", number: "002"),
        Pokemon(name: "Venusaur", number: "003"),
        Pokemon(name: "Charmander", number: "004"),
        Pokemon(name: "Charmeleon", number: "005"),
        Pokemon(name: "Charizard", number: "006"),
        Pokemon(name: "Squirtle", number: "007"),
        Pokemon(name: "Wartortle", number: "008"),
        Pokemon(name: "Blastoise", number: "009"),
        Pokemon(name: "Caterpie", number: "010"),
        Pokemon(name: "Metapod", number: "011"),
        Pokemon(name: "Butterfree", number: "012"),
        Pokemon(name: "Weedle", number: "013"),
        Pokemon(name: "Kakuna", number: "014"),
        Pokemon(name: "Beedrill", number: "015"),
        Pokemon(name: "Pidgey", number: "016"),
        Pokemon(name: "Pidgeotto", number: "017"),
        Pokemon(name: "Pidgeot", number: "018"),
        Pokemon(name: "Rattata", number: "019"),
        Pokemon(name: "Raticate", number: "020"),
        Pokemon(name: "Spearow", number: "021"),
        Pokemon(name: "Fearow", number: "022"),
        Pokemon(name: "Ekans", number: "023"),
        Pokemon(name: "Arbok", number: "024"),
        Pokemon(name: "Pikachu", number: "025"),
        Pokemon(name: "Raichu", number: "026"),
        Pokemon(name: "Sandshrew", number: "027"),
        Pokemon(name: "Sandslash", number: "028"),
        Pokemon(name: "Nidoran♀", number: "029"),
        Pokemon(name: "Nidorina", number: "030"),
        Pokemon(name: "Nidoqueen", number: "031"),
        Pokemon(name: "Nidoran♂", number: "032"),
        Pokemon(name: "Nidorino", number: "033"),
        Pokemon(name: "Nidoking", number: "034"),
        Pokemon(name: "Clefairy", number: "035"),
        Pokemon(name: "Clefable", number: "036"),
        Pokemon(name: "Vulpix", number: "037"),
        Pokemon(name: "Ninetales", number: "038"),
        Pokemon(name: "Jigglypuff", number: "039"),
        Pokemon(name: "Wigglytuff", number: "040"),
        Pokemon(name: "Zubat", number: "041"),
        Pokemon(name: "Golbat", number: "042"),
        Pokemon(name: "Oddish", number: "043"),
        Pokemon(name: "Gloom", number: "044"),
        Pokemon(name: "Vileplume", number: "045"),
        Pokemon(name: "Paras", number: "046"),
        Pokemon(name: "Parasect", number: "047"),
        Pokemon(name: "Venonat", number: "048"),
        Pokemon(name: "Venomoth", number: "049"),
        Pokemon(name: "Diglett", number: "050"),
        Pokemon(name: "Dugtrio", number: "051"),
        Pokemon(name: "Meowth", number: "052"),
        Pokemon(name: "Persian", number: "053"),
        Pokemon(name: "Psyduck", number: "054"),
        Pokemon(name: "Golduck", number: "055"),
        Pokemon(name: "Mankey", number: "056"),
        Pokemon(name: "Primeape", number: "057"),
        Pokemon(name: "Growlithe", number: "058"),
        Pokemon(name: "Arcanine", number: "059"),
        Pokemon(name: "Poliwag", number: "060"),
        Pokemon(name: "Poliwhirl", number: "061"),
        Pokemon(name: "Poliwrath", number: "062"),
        Pokemon(name: "Abra", number: "063"),
        Pokemon(name: "Kadabra", number: "064"),
        Pokemon(name: "Alakazam", number: "065"),
        Pokemon(name: "Machop", number: "066"),
        Pokemon(name: "Machoke", number: "067"),
        Pokemon(name: "Machamp", number: "068"),
        Pokemon(name: "Bellsprout", number: "069"),
        Pokemon(name: "Weepinbell", number: "070"),
        Pokemon(name: "Victreebel", number: "071"),
        Pokemon(name: "Tentacool", number: "072"),
        Pokemon(name: "Tentacruel", number: "073"),
        Pokemon(name: "Geodude", number: "074"),
        Pokemon(name: "Graveler", number: "075"),
        Pokemon(name: "Golem", number: "076"),
        Pokemon(name: "Ponyta", number: "077"),
        Pokemon(name: "Rapidash", number: "078"),
        Pokemon(name: "Slowpoke", number: "079"),
        Pokemon(name: "Slowbro", number: "080"),
        Pokemon(name: "Magnemite", number: "081"),
        Pokemon(name: "Magneton", number: "082"),
        Pokemon(name: "Farfetch’d", number: "083"),
        Pokemon(name: "Doduo", number: "084"),
        Pokemon(name: "Dodrio", number: "085"),
        Pokemon(name: "Seel", number: "086"),
        Pokemon(name: "Dewgong", number: "087"),
        Pokemon(name: "Grimer", number: "088"),
        Pokemon(name: "Muk", number: "089"),
        Pokemon(name: "Shellder", number: "090"),
        Pokemon(name: "Cloyster", number: "091"),
        Pokemon(name: "Gastly", number: "092"),
        Pokemon(name: "Haunter", number: "093"),
        Pokemon(name: "Gengar", number: "094"),
        Pokemon(name: "Onix", number: "095"),
        Pokemon(name: "Drowzee", number: "096"),
        Pokemon(name: "Hypno", number: "097"),
        Pokemon(name: "Krabby", number: "098"),
        Pokemon(name: "Kingler", number: "099"),
        Pokemon(name: "Voltorb", number: "100"),
        Pokemon(name: "Electrode", number: "101"),
        Pokemon(name: "Exeggcute", number: "102"),
        Pokemon(name: "Exeggutor", number: "103"),
        Pokemon(name: "Cubone", number: "104"),
        Pokemon(name: "Marowak", number: "105"),
        Pokemon(name: "Hitmonlee", number: "106"),
        Pokemon(name: "Hitmonchan", number: "107"),
        Pokemon(name: "Lickitung", number: "108"),
        Pokemon(name: "Koffing", number: "109"),
        Pokemon(name: "Weezing", number: "110"),
        Pokemon(name: "Rhyhorn", number: "111"),
        Pokemon(name: "Rhydon", number: "112"),
        Pokemon(name: "Chansey", number: "113"),
        Pokemon(name: "Tangela", number: "114"),
        Pokemon(name: "Kangaskhan", number: "115"),
        Pokemon(name: "Horsea", number: "116"),
        Pokemon(name: "Seadra", number: "117"),
        Pokemon(name: "Goldeen", number: "118"),
        Pokemon(name: "Seaking", number: "119"),
        Pokemon(name: "Staryu", number: "120"),
        Pokemon(name: "Starmie", number: "121"),
        Pokemon(name: "Mr. Mime", number: "122"),
        Pokemon(name: "Scyther", number: "123"),
        Pokemon(name: "Jynx", number: "124"),
        Pokemon(name: "Electabuzz", number: "125"),
        Pokemon(name: "Magmar", number: "126"),
        Pokemon(name: "Pinsir", number: "127"),
        Pokemon(name: "Tauros", number: "128"),
        Pokemon(name: "Magikarp", number: "129"),
        Pokemon(name: "Gyarados", number: "130"),
        Pokemon(name: "Lapras", number: "131"),
        Pokemon(name: "Ditto", number: "132"),
        Pokemon(name: "Eevee", number: "133"),
        Pokemon(name: "Vaporeon", number: "134"),
        Pokemon(name: "Jolteon", number: "135"),
        Pokemon(name: "Flareon", number: "136"),
        Pokemon(name: "Porygon", number: "137"),
        Pokemon(name: "Omanyte", number: "138"),
        Pokemon(name: "Omastar", number: "139"),
        Pokemon(name: "Kabuto", number: "140"),
        Pokemon(name: "Kabutops", number: "141"),
        Pokemon(name: "Aerodactyl", number: "142"),
        Pokemon(name: "Snorlax", number: "143"),
        Pokemon(name: "Articuno", number: "144"),
        Pokemon(name: "Zapdos", number: "145"),
        Pokemon(name: "Moltres", number: "146"),
        Pokemon(name: "Dratini", number: "147"),
        Pokemon(name: "Dragonair", number: "148"),
        Pokemon(name: "Dragonite", number: "149"),
        Pokemon(name: "Mewtwo", number: "150"),
        Pokemon(name: "Mew", number: "151"),
        Pokemon(name: "Chikorita", number: "152"),
        Pokemon(name: "Bayleef", number: "153"),
        Pokemon(name: "Meganium", number: "154"),
        Pokemon(name: "Cyndaquil", number: "155"),
        Pokemon(name: "Quilava", number: "156"),
        Pokemon(name: "Typhlosion", number: "157"),
        Pokemon(name: "Totodile", number: "158"),
        Pokemon(name: "Croconaw", number: "159"),
        Pokemon(name: "Feraligatr", number: "160"),
        Pokemon(name: "Sentret", number: "161"),
        Pokemon(name: "Furret", number: "162"),
        Pokemon(name: "Hoothoot", number: "163"),
        Pokemon(name: "Noctowl", number: "164"),
        Pokemon(name: "Ledyba", number: "165"),
        Pokemon(name: "Ledian", number: "166"),
        Pokemon(name: "Spinarak", number: "167"),
        Pokemon(name: "Ariados", number: "168"),
        Pokemon(name: "Crobat", number: "169"),
        Pokemon(name: "Chinchou", number: "170"),
        Pokemon(name: "Lanturn", number: "171"),
        Pokemon(name: "Pichu", number: "172"),
        Pokemon(name: "Cleffa", number: "173"),
        Pokemon(name: "Igglybuff", number: "174"),
        Pokemon(name: "Togepi", number: "175"),
        Pokemon(name: "Togetic", number: "176"),
        Pokemon(name: "Natu", number: "177"),
        Pokemon(name: "Xatu", number: "178"),
        Pokemon(name: "Mareep", number: "179"),
        Pokemon(name: "Flaaffy", number: "180"),
        Pokemon(name: "Ampharos", number: "181"),
        Pokemon(name: "Bellossom", number: "182"),
        Pokemon(name: "Marill", number: "183"),
        Pokemon(name: "Azumarill", number: "184"),
        Pokemon(name: "Sudowoodo", number: "185"),
        Pokemon(name: "Politoed", number: "186"),
        Pokemon(name: "Hoppip", number: "187"),
        Pokemon(name: "Skiploom", number: "188"),
        Pokemon(name: "Jumpluff", number: "189"),
        Pokemon(name: "Aipom", number: "190"),
        Pokemon(name: "Sunkern", number: "191"),
        Pokemon(name: "Sunflora", number: "192"),
        Pokemon(name: "Yanma", number: "193"),
        Pokemon(name: "Wooper", number: "194"),
        Pokemon(name: "Quagsire", number: "195"),
        Pokemon(name: "Espeon", number: "196"),
        Pokemon(name: "Umbreon", number: "197"),
        Pokemon(name: "Murkrow", number: "198"),
        Pokemon(name: "Slowking", number: "199"),
        Pokemon(name: "Misdreavus", number: "200"),
        Pokemon(name: "Unown", number: "201"),
        Pokemon(name: "Wobbuffet", number: "202"),
        Pokemon(name: "Girafarig", number: "203"),
        Pokemon(name: "Pineco", number: "204"),
        Pokemon(name: "Forretress", number: "205"),
        Pokemon(name: "Dunsparce", number: "206"),
        Pokemon(name: "Gligar", number: "207"),
        Pokemon(name: "Steelix", number: "208"),
        Pokemon(name: "Snubbull", number: "209"),
        Pokemon(name: "Granbull", number: "210"),
        Pokemon(name: "Qwilfish", number: "211"),
        Pokemon(name: "Scizor", number: "212"),
        Pokemon(name: "Shuckle", number: "213"),
        Pokemon(name: "Heracross", number: "214"),
        Pokemon(name: "Sneasel", number: "215"),
        Pokemon(name: "Teddiursa", number: "216"),
        Pokemon(name: "Ursaring", number: "217"),
        Pokemon(name: "Slugma", number: "218"),
        Pokemon(name: "Magcargo", number: "219"),
        Pokemon(name: "Swinub", number: "220"),
        Pokemon(name: "Piloswine", number: "221"),
        Pokemon(name: "Corsola", number: "222"),
        Pokemon(name: "Remoraid", number: "223"),
        Pokemon(name: "Octillery", number: "224"),
        Pokemon(name: "Delibird", number: "225"),
        Pokemon(name: "Mantine", number: "226"),
        Pokemon(name: "Skarmory", number: "227"),
        Pokemon(name: "Houndour", number: "228"),
        Pokemon(name: "Houndoom", number: "229"),
        Pokemon(name: "Kingdra", number: "230"),
        Pokemon(name: "Phanpy", number: "231"),
        Pokemon(name: "Donphan", number: "232"),
        Pokemon(name: "Porygon2", number: "233"),
        Pokemon(name: "Stantler", number: "234"),
        Pokemon(name: "Smeargle", number: "235"),
        Pokemon(name: "Tyrogue", number: "236"),
        Pokemon(name: "Hitmontop", number: "237"),
        Pokemon(name: "Smoochum", number: "238"),
        Pokemon(name: "Elekid", number: "239"),
        Pokemon(name: "Magby", number: "240"),
        Pokemon(name: "Miltank", number: "241"),
        Pokemon(name: "Blissey", number: "242"),
        Pokemon(name: "Raikou", number: "243"),
        Pokemon(name: "Entei", number: "244"),
        Pokemon(name: "Suicune", number: "245"),
        Pokemon(name: "Larvitar", number: "246"),
        Pokemon(name: "Pupitar", number: "247"),
        Pokemon(name: "Tyranitar", number: "248"),
        Pokemon(name: "Lugia", number: "249"),
        Pokemon(name: "Ho-Oh", number: "250"),
        Pokemon(name: "Celebi", number: "251"),
        Pokemon(name: "Treecko", number: "252"),
        Pokemon(name: "Grovyle", number: "253"),
        Pokemon(name: "Sceptile", number: "254"),
        Pokemon(name: "Torchic", number: "255"),
        Pokemon(name: "Combusken", number: "256"),
        Pokemon(name: "Blaziken", number: "257"),
        Pokemon(name: "Mudkip", number: "258"),
        Pokemon(name: "Marshtomp", number: "259"),
        Pokemon(name: "Swampert", number: "260"),
        Pokemon(name: "Poochyena", number: "261"),
        Pokemon(name: "Mightyena", number: "262"),
        Pokemon(name: "Zigzagoon", number: "263"),
        Pokemon(name: "Linoone", number: "264"),
        Pokemon(name: "Wurmple", number: "265"),
        Pokemon(name: "Silcoon", number: "266"),
        Pokemon(name: "Beautifly", number: "267"),
        Pokemon(name: "Cascoon", number: "268"),
        Pokemon(name: "Dustox", number: "269"),
        Pokemon(name: "Lotad", number: "270"),
        Pokemon(name: "Lombre", number: "271"),
        Pokemon(name: "Ludicolo", number: "272"),
        Pokemon(name: "Seedot", number: "273"),
        Pokemon(name: "Nuzleaf", number: "274"),
        Pokemon(name: "Shiftry", number: "275"),
        Pokemon(name: "Taillow", number: "276"),
        Pokemon(name: "Swellow", number: "277"),
        Pokemon(name: "Wingull", number: "278"),
        Pokemon(name: "Pelipper", number: "279"),
        Pokemon(name: "Ralts", number: "280"),
        Pokemon(name: "Kirlia", number: "281"),
        Pokemon(name: "Gardevoir", number: "282"),
        Pokemon(name: "Surskit", number: "283"),
        Pokemon(name: "Masquerain", number: "284"),
        Pokemon(name: "Shroomish", number: "285"),
        Pokemon(name: "Breloom", number: "286"),
        Pokemon(name: "Slakoth", number: "287"),
        Pokemon(name: "Vigoroth", number: "288"),
        Pokemon(name: "Slaking", number: "289"),
        Pokemon(name: "Nincada", number: "290"),
        Pokemon(name: "Ninjask", number: "291"),
        Pokemon(name: "Shedinja", number: "292"),
        Pokemon(name: "Whismur", number: "293"),
        Pokemon(name: "Loudred", number: "294"),
        Pokemon(name: "Exploud", number: "295"),
        Pokemon(name: "Makuhita", number: "296"),
        Pokemon(name: "Hariyama", number: "297"),
        Pokemon(name: "Azurill", number: "298"),
        Pokemon(name: "Nosepass", number: "299"),
        Pokemon(name: "Skitty", number: "300"),
        Pokemon(name: "Delcatty", number: "301"),
        Pokemon(name: "Sableye", number: "302"),
        Pokemon(name: "Mawile", number: "303"),
        Pokemon(name: "Aron", number: "304"),
        Pokemon(name: "Lairon", number: "305"),
        Pokemon(name: "Aggron", number: "306"),
        Pokemon(name: "Meditite", number: "307"),
        Pokemon(name: "Medicham", number: "308"),
        Pokemon(name: "Electrike", number: "309"),
        Pokemon(name: "Manectric", number: "310"),
        Pokemon(name: "Plusle", number: "311"),
        Pokemon(name: "Minun", number: "312"),
        Pokemon(name: "Volbeat", number: "313"),
        Pokemon(name: "Illumise", number: "314"),
        Pokemon(name: "Roselia", number: "315"),
        Pokemon(name: "Gulpin", number: "316"),
        Pokemon(name: "Swalot", number: "317"),
        Pokemon(name: "Carvanha", number: "318"),
        Pokemon(name: "Sharpedo", number: "319"),
        Pokemon(name: "Wailmer", number: "320"),
        Pokemon(name: "Wailord", number: "321"),
        Pokemon(name: "Numel", number: "322"),
        Pokemon(name: "Camerupt", number: "323"),
        Pokemon(name: "Torkoal", number: "324"),
        Pokemon(name: "Spoink", number: "325"),
        Pokemon(name: "Grumpig", number: "326"),
        Pokemon(name: "Spinda", number: "327"),
        Pokemon(name: "Trapinch", number: "328"),
        Pokemon(name: "Vibrava", number: "329"),
        Pokemon(name: "Flygon", number: "330"),
        Pokemon(name: "Cacnea", number: "331"),
        Pokemon(name: "Cacturne", number: "332"),
        Pokemon(name: "Swablu", number: "333"),
        Pokemon(name: "Altaria", number: "334"),
        Pokemon(name: "Zangoose", number: "335"),
        Pokemon(name: "Seviper", number: "336"),
        Pokemon(name: "Lunatone", number: "337"),
        Pokemon(name: "Solrock", number: "338"),
        Pokemon(name: "Barboach", number: "339"),
        Pokemon(name: "Whiscash", number: "340"),
        Pokemon(name: "Corphish", number: "341"),
        Pokemon(name: "Crawdaunt", number: "342"),
        Pokemon(name: "Baltoy", number: "343"),
        Pokemon(name: "Claydol", number: "344"),
        Pokemon(name: "Lileep", number: "345"),
        Pokemon(name: "Cradily", number: "346"),
        Pokemon(name: "Anorith", number: "347"),
        Pokemon(name: "Armaldo", number: "348"),
        Pokemon(name: "Feebas", number: "349"),
        Pokemon(name: "Milotic", number: "350"),
        Pokemon(name: "Castform", number: "351"),
        Pokemon(name: "Kecleon", number: "352"),
        Pokemon(name: "Shuppet", number: "353"),
        Pokemon(name: "Banette", number: "354"),
        Pokemon(name: "Duskull", number: "355"),
        Pokemon(name: "Dusclops", number: "356"),
        Pokemon(name: "Tropius", number: "357"),
        Pokemon(name: "Chimecho", number: "358"),
        Pokemon(name: "Absol", number: "359"),
        Pokemon(name: "Wynaut", number: "360"),
        Pokemon(name: "Snorunt", number: "361"),
        Pokemon(name: "Glalie", number: "362"),
        Pokemon(name: "Spheal", number: "363"),
        Pokemon(name: "Sealeo", number: "364"),
        Pokemon(name: "Walrein", number: "365"),
        Pokemon(name: "Clamperl", number: "366"),
        Pokemon(name: "Huntail", number: "367"),
        Pokemon(name: "Gorebyss", number: "368"),
        Pokemon(name: "Relicanth", number: "369"),
        Pokemon(name: "Luvdisc", number: "370"),
        Pokemon(name: "Bagon", number: "371"),
        Pokemon(name: "Shelgon", number: "372"),
        Pokemon(name: "Salamence", number: "373"),
        Pokemon(name: "Beldum", number: "374"),
        Pokemon(name: "Metang", number: "375"),
        Pokemon(name: "Metagross", number: "376"),
        Pokemon(name: "Regirock", number: "377"),
        Pokemon(name: "Regice", number: "378"),
        Pokemon(name: "Registeel", number: "379"),
        Pokemon(name: "Latias", number: "380"),
        Pokemon(name: "Latios", number: "381"),
        Pokemon(name: "Kyogre", number: "382"),
        Pokemon(name: "Groudon", number: "383"),
        Pokemon(name: "Rayquaza", number: "384"),
        Pokemon(name: "Jirachi", number: "385"),
        Pokemon(name: "Deoxys", number: "386"),
//        Pokemon(name: "Turtwig", number: "387"),
//        Pokemon(name: "Grotle", number: "388"),
//        Pokemon(name: "Torterra", number: "389"),
//        Pokemon(name: "Chimchar", number: "390"),
//        Pokemon(name: "Monferno", number: "391"),
//        Pokemon(name: "Infernape", number: "392"),
//        Pokemon(name: "Piplup", number: "393"),
//        Pokemon(name: "Prinplup", number: "394"),
//        Pokemon(name: "Empoleon", number: "395"),
//        Pokemon(name: "Starly", number: "396"),
//        Pokemon(name: "Staravia", number: "397"),
//        Pokemon(name: "Staraptor", number: "398"),
//        Pokemon(name: "Bidoof", number: "399"),
//        Pokemon(name: "Bibarel", number: "400"),
//        Pokemon(name: "Kricketot", number: "401"),
//        Pokemon(name: "Kricketune", number: "402"),
//        Pokemon(name: "Shinx", number: "403"),
//        Pokemon(name: "Luxio", number: "404"),
//        Pokemon(name: "Luxray", number: "405"),
//        Pokemon(name: "Budew", number: "406"),
//        Pokemon(name: "Roserade", number: "407"),
//        Pokemon(name: "Cranidos", number: "408"),
//        Pokemon(name: "Rampardos", number: "409"),
//        Pokemon(name: "Shieldon", number: "410"),
//        Pokemon(name: "Bastiodon", number: "411"),
//        Pokemon(name: "Burmy", number: "412"),
//        Pokemon(name: "Wormadam", number: "413"),
//        Pokemon(name: "Mothim", number: "414"),
//        Pokemon(name: "Combee", number: "415"),
//        Pokemon(name: "Vespiquen", number: "416"),
//        Pokemon(name: "Pachirisu", number: "417"),
//        Pokemon(name: "Buizel", number: "418"),
//        Pokemon(name: "Floatzel", number: "419"),
//        Pokemon(name: "Cherubi", number: "420"),
//        Pokemon(name: "Cherrim", number: "421"),
//        Pokemon(name: "Shellos", number: "422"),
//        Pokemon(name: "Gastrodon", number: "423"),
//        Pokemon(name: "Ambipom", number: "424"),
//        Pokemon(name: "Drifloon", number: "425"),
//        Pokemon(name: "Drifblim", number: "426"),
//        Pokemon(name: "Buneary", number: "427"),
//        Pokemon(name: "Lopunny", number: "428"),
//        Pokemon(name: "Mismagius", number: "429"),
//        Pokemon(name: "Honchkrow", number: "430"),
//        Pokemon(name: "Glameow", number: "431"),
//        Pokemon(name: "Purugly", number: "432"),
//        Pokemon(name: "Chingling", number: "433"),
//        Pokemon(name: "Stunky", number: "434"),
//        Pokemon(name: "Skuntank", number: "435"),
//        Pokemon(name: "Bronzor", number: "436"),
//        Pokemon(name: "Bronzong", number: "437"),
//        Pokemon(name: "Bonsly", number: "438"),
//        Pokemon(name: "Mime Jr.", number: "439"),
//        Pokemon(name: "Happiny", number: "440"),
//        Pokemon(name: "Chatot", number: "441"),
//        Pokemon(name: "Spiritomb", number: "442"),
//        Pokemon(name: "Gible", number: "443"),
//        Pokemon(name: "Gabite", number: "444"),
//        Pokemon(name: "Garchomp", number: "445"),
//        Pokemon(name: "Munchlax", number: "446"),
//        Pokemon(name: "Riolu", number: "447"),
//        Pokemon(name: "Lucario", number: "448"),
//        Pokemon(name: "Hippopotas", number: "449"),
//        Pokemon(name: "Hippowdon", number: "450"),
//        Pokemon(name: "Skorupi", number: "451"),
//        Pokemon(name: "Drapion", number: "452"),
//        Pokemon(name: "Croagunk", number: "453"),
//        Pokemon(name: "Toxicroak", number: "454"),
//        Pokemon(name: "Carnivine", number: "455"),
//        Pokemon(name: "Finneon", number: "456"),
//        Pokemon(name: "Lumineon", number: "457"),
//        Pokemon(name: "Mantyke", number: "458"),
//        Pokemon(name: "Snover", number: "459"),
//        Pokemon(name: "Abomasnow", number: "460"),
//        Pokemon(name: "Weavile", number: "461"),
//        Pokemon(name: "Magnezone", number: "462"),
//        Pokemon(name: "Lickilicky", number: "463"),
//        Pokemon(name: "Rhyperior", number: "464"),
//        Pokemon(name: "Tangrowth", number: "465"),
//        Pokemon(name: "Electivire", number: "466"),
//        Pokemon(name: "Magmortar", number: "467"),
//        Pokemon(name: "Togekiss", number: "468"),
//        Pokemon(name: "Yanmega", number: "469"),
//        Pokemon(name: "Leafeon", number: "470"),
//        Pokemon(name: "Glaceon", number: "471"),
//        Pokemon(name: "Gliscor", number: "472"),
//        Pokemon(name: "Mamoswine", number: "473"),
//        Pokemon(name: "Porygon-Z", number: "474"),
//        Pokemon(name: "Gallade", number: "475"),
//        Pokemon(name: "Probopass", number: "476"),
//        Pokemon(name: "Dusknoir", number: "477"),
//        Pokemon(name: "Froslass", number: "478"),
//        Pokemon(name: "Rotom", number: "479"),
//        Pokemon(name: "Uxie", number: "480"),
//        Pokemon(name: "Mesprit", number: "481"),
//        Pokemon(name: "Azelf", number: "482"),
//        Pokemon(name: "Dialga", number: "483"),
//        Pokemon(name: "Palkia", number: "484"),
//        Pokemon(name: "Heatran", number: "485"),
//        Pokemon(name: "Regigigas", number: "486"),
//        Pokemon(name: "Giratina", number: "487"),
//        Pokemon(name: "Cresselia", number: "488"),
//        Pokemon(name: "Phione", number: "489"),
//        Pokemon(name: "Manaphy", number: "490"),
//        Pokemon(name: "Darkrai", number: "491"),
//        Pokemon(name: "Shaymin", number: "492"),
//        Pokemon(name: "Arceus", number: "493"),
//        Pokemon(name: "Victini", number: "494"),
//        Pokemon(name: "Snivy", number: "495"),
//        Pokemon(name: "Servine", number: "496"),
//        Pokemon(name: "Serperior", number: "497"),
//        Pokemon(name: "Tepig", number: "498"),
//        Pokemon(name: "Pignite", number: "499"),
//        Pokemon(name: "Emboar", number: "500"),
//        Pokemon(name: "Oshawott", number: "501"),
//        Pokemon(name: "Dewott", number: "502"),
//        Pokemon(name: "Samurott", number: "503"),
//        Pokemon(name: "Patrat", number: "504"),
//        Pokemon(name: "Watchog", number: "505"),
//        Pokemon(name: "Lillipup", number: "506"),
//        Pokemon(name: "Herdier", number: "507"),
//        Pokemon(name: "Stoutland", number: "508"),
//        Pokemon(name: "Purrloin", number: "509"),
//        Pokemon(name: "Liepard", number: "510"),
//        Pokemon(name: "Pansage", number: "511"),
//        Pokemon(name: "Simisage", number: "512"),
//        Pokemon(name: "Pansear", number: "513"),
//        Pokemon(name: "Simisear", number: "514"),
//        Pokemon(name: "Panpour", number: "515"),
//        Pokemon(name: "Simipour", number: "516"),
//        Pokemon(name: "Munna", number: "517"),
//        Pokemon(name: "Musharna", number: "518"),
//        Pokemon(name: "Pidove", number: "519"),
//        Pokemon(name: "Tranquill", number: "520"),
//        Pokemon(name: "Unfezant", number: "521"),
//        Pokemon(name: "Blitzle", number: "522"),
//        Pokemon(name: "Zebstrika", number: "523"),
//        Pokemon(name: "Roggenrola", number: "524"),
//        Pokemon(name: "Boldore", number: "525"),
//        Pokemon(name: "Gigalith", number: "526"),
//        Pokemon(name: "Woobat", number: "527"),
//        Pokemon(name: "Swoobat", number: "528"),
//        Pokemon(name: "Drilbur", number: "529"),
//        Pokemon(name: "Excadrill", number: "530"),
//        Pokemon(name: "Audino", number: "531"),
//        Pokemon(name: "Timburr", number: "532"),
//        Pokemon(name: "Gurdurr", number: "533"),
//        Pokemon(name: "Conkeldurr", number: "534"),
//        Pokemon(name: "Tympole", number: "535"),
//        Pokemon(name: "Palpitoad", number: "536"),
//        Pokemon(name: "Seismitoad", number: "537"),
//        Pokemon(name: "Throh", number: "538"),
//        Pokemon(name: "Sawk", number: "539"),
//        Pokemon(name: "Sewaddle", number: "540"),
//        Pokemon(name: "Swadloon", number: "541"),
//        Pokemon(name: "Leavanny", number: "542"),
//        Pokemon(name: "Venipede", number: "543"),
//        Pokemon(name: "Whirlipede", number: "544"),
//        Pokemon(name: "Scolipede", number: "545"),
//        Pokemon(name: "Cottonee", number: "546"),
//        Pokemon(name: "Whimsicott", number: "547"),
//        Pokemon(name: "Petilil", number: "548"),
//        Pokemon(name: "Lilligant", number: "549"),
//        Pokemon(name: "Basculin", number: "550"),
//        Pokemon(name: "Sandile", number: "551"),
//        Pokemon(name: "Krokorok", number: "552"),
//        Pokemon(name: "Krookodile", number: "553"),
//        Pokemon(name: "Darumaka", number: "554"),
//        Pokemon(name: "Darmanitan", number: "555"),
//        Pokemon(name: "Maractus", number: "556"),
//        Pokemon(name: "Dwebble", number: "557"),
//        Pokemon(name: "Crustle", number: "558"),
//        Pokemon(name: "Scraggy", number: "559"),
//        Pokemon(name: "Scrafty", number: "560"),
//        Pokemon(name: "Sigilyph", number: "561"),
//        Pokemon(name: "Yamask", number: "562"),
//        Pokemon(name: "Cofagrigus", number: "563"),
//        Pokemon(name: "Tirtouga", number: "564"),
//        Pokemon(name: "Carracosta", number: "565"),
//        Pokemon(name: "Archen", number: "566"),
//        Pokemon(name: "Archeops", number: "567"),
//        Pokemon(name: "Trubbish", number: "568"),
//        Pokemon(name: "Garbodor", number: "569"),
//        Pokemon(name: "Zorua", number: "570"),
//        Pokemon(name: "Zoroark", number: "571"),
//        Pokemon(name: "Minccino", number: "572"),
//        Pokemon(name: "Cinccino", number: "573"),
//        Pokemon(name: "Gothita", number: "574"),
//        Pokemon(name: "Gothorita", number: "575"),
//        Pokemon(name: "Gothitelle", number: "576"),
//        Pokemon(name: "Solosis", number: "577"),
//        Pokemon(name: "Duosion", number: "578"),
//        Pokemon(name: "Reuniclus", number: "579"),
//        Pokemon(name: "Ducklett", number: "580"),
//        Pokemon(name: "Swanna", number: "581"),
//        Pokemon(name: "Vanillite", number: "582"),
//        Pokemon(name: "Vanillish", number: "583"),
//        Pokemon(name: "Vanilluxe", number: "584"),
//        Pokemon(name: "Deerling", number: "585"),
//        Pokemon(name: "Sawsbuck", number: "586"),
//        Pokemon(name: "Emolga", number: "587"),
//        Pokemon(name: "Karrablast", number: "588"),
//        Pokemon(name: "Escavalier", number: "589"),
//        Pokemon(name: "Foongus", number: "590"),
//        Pokemon(name: "Amoonguss", number: "591"),
//        Pokemon(name: "Frillish", number: "592"),
//        Pokemon(name: "Jellicent", number: "593"),
//        Pokemon(name: "Alomomola", number: "594"),
//        Pokemon(name: "Joltik", number: "595"),
//        Pokemon(name: "Galvantula", number: "596"),
//        Pokemon(name: "Ferroseed", number: "597"),
//        Pokemon(name: "Ferrothorn", number: "598"),
//        Pokemon(name: "Klink", number: "599"),
//        Pokemon(name: "Klang", number: "600"),
//        Pokemon(name: "Klinklang", number: "601"),
//        Pokemon(name: "Tynamo", number: "602"),
//        Pokemon(name: "Eelektrik", number: "603"),
//        Pokemon(name: "Eelektross", number: "604"),
//        Pokemon(name: "Elgyem", number: "605"),
//        Pokemon(name: "Beheeyem", number: "606"),
//        Pokemon(name: "Litwick", number: "607"),
//        Pokemon(name: "Lampent", number: "608"),
//        Pokemon(name: "Chandelure", number: "609"),
//        Pokemon(name: "Axew", number: "610"),
//        Pokemon(name: "Fraxure", number: "611"),
//        Pokemon(name: "Haxorus", number: "612"),
//        Pokemon(name: "Cubchoo", number: "613"),
//        Pokemon(name: "Beartic", number: "614"),
//        Pokemon(name: "Cryogonal", number: "615"),
//        Pokemon(name: "Shelmet", number: "616"),
//        Pokemon(name: "Accelgor", number: "617"),
//        Pokemon(name: "Stunfisk", number: "618"),
//        Pokemon(name: "Mienfoo", number: "619"),
//        Pokemon(name: "Mienshao", number: "620"),
//        Pokemon(name: "Druddigon", number: "621"),
//        Pokemon(name: "Golett", number: "622"),
//        Pokemon(name: "Golurk", number: "623"),
//        Pokemon(name: "Pawniard", number: "624"),
//        Pokemon(name: "Bisharp", number: "625"),
//        Pokemon(name: "Bouffalant", number: "626"),
//        Pokemon(name: "Rufflet", number: "627"),
//        Pokemon(name: "Braviary", number: "628"),
//        Pokemon(name: "Vullaby", number: "629"),
//        Pokemon(name: "Mandibuzz", number: "630"),
//        Pokemon(name: "Heatmor", number: "631"),
//        Pokemon(name: "Durant", number: "632"),
//        Pokemon(name: "Deino", number: "633"),
//        Pokemon(name: "Zweilous", number: "634"),
//        Pokemon(name: "Hydreigon", number: "635"),
//        Pokemon(name: "Larvesta", number: "636"),
//        Pokemon(name: "Volcarona", number: "637"),
//        Pokemon(name: "Cobalion", number: "638"),
//        Pokemon(name: "Terrakion", number: "639"),
//        Pokemon(name: "Virizion", number: "640"),
//        Pokemon(name: "Tornadus", number: "641"),
//        Pokemon(name: "Thundurus", number: "642"),
//        Pokemon(name: "Reshiram", number: "643"),
//        Pokemon(name: "Zekrom", number: "644"),
//        Pokemon(name: "Landorus", number: "645"),
//        Pokemon(name: "Kyurem", number: "646"),
//        Pokemon(name: "Keldeo", number: "647"),
//        Pokemon(name: "Meloetta", number: "648"),
//        Pokemon(name: "Genesect", number: "649"),
//        Pokemon(name: "Chespin", number: "650"),
//        Pokemon(name: "Quilladin", number: "651"),
//        Pokemon(name: "Chesnaught", number: "652"),
//        Pokemon(name: "Fennekin", number: "653"),
//        Pokemon(name: "Braixen", number: "654"),
//        Pokemon(name: "Delphox", number: "655"),
//        Pokemon(name: "Froakie", number: "656"),
//        Pokemon(name: "Frogadier", number: "657"),
//        Pokemon(name: "Greninja", number: "658"),
//        Pokemon(name: "Bunnelby", number: "659"),
//        Pokemon(name: "Diggersby", number: "660"),
//        Pokemon(name: "Fletchling", number: "661"),
//        Pokemon(name: "Fletchinder", number: "662"),
//        Pokemon(name: "Talonflame", number: "663"),
//        Pokemon(name: "Scatterbug", number: "664"),
//        Pokemon(name: "Spewpa", number: "665"),
//        Pokemon(name: "Vivillon", number: "666"),
//        Pokemon(name: "Litleo", number: "667"),
//        Pokemon(name: "Pyroar", number: "668"),
//        Pokemon(name: "Flabébé", number: "669"),
//        Pokemon(name: "Floette", number: "670"),
//        Pokemon(name: "Florges", number: "671"),
//        Pokemon(name: "Skiddo", number: "672"),
//        Pokemon(name: "Gogoat", number: "673"),
//        Pokemon(name: "Pancham", number: "674"),
//        Pokemon(name: "Pangoro", number: "675"),
//        Pokemon(name: "Furfrou", number: "676"),
//        Pokemon(name: "Espurr", number: "677"),
//        Pokemon(name: "Meowstic", number: "678"),
//        Pokemon(name: "Honedge", number: "679"),
//        Pokemon(name: "Doublade", number: "680"),
//        Pokemon(name: "Aegislash", number: "681"),
//        Pokemon(name: "Spritzee", number: "682"),
//        Pokemon(name: "Aromatisse", number: "683"),
//        Pokemon(name: "Swirlix", number: "684"),
//        Pokemon(name: "Slurpuff", number: "685"),
//        Pokemon(name: "Inkay", number: "686"),
//        Pokemon(name: "Malamar", number: "687"),
//        Pokemon(name: "Binacle", number: "688"),
//        Pokemon(name: "Barbaracle", number: "689"),
//        Pokemon(name: "Skrelp", number: "690"),
//        Pokemon(name: "Dragalge", number: "691"),
//        Pokemon(name: "Clauncher", number: "692"),
//        Pokemon(name: "Clawitzer", number: "693"),
//        Pokemon(name: "Helioptile", number: "694"),
//        Pokemon(name: "Heliolisk", number: "695"),
//        Pokemon(name: "Tyrunt", number: "696"),
//        Pokemon(name: "Tyrantrum", number: "697"),
//        Pokemon(name: "Amaura", number: "698"),
//        Pokemon(name: "Aurorus", number: "699"),
//        Pokemon(name: "Sylveon", number: "700"),
//        Pokemon(name: "Hawlucha", number: "701"),
//        Pokemon(name: "Dedenne", number: "702"),
//        Pokemon(name: "Carbink", number: "703"),
//        Pokemon(name: "Goomy", number: "704"),
//        Pokemon(name: "Sliggoo", number: "705"),
//        Pokemon(name: "Goodra", number: "706"),
//        Pokemon(name: "Klefki", number: "707"),
//        Pokemon(name: "Phantump", number: "708"),
//        Pokemon(name: "Trevenant", number: "709"),
//        Pokemon(name: "Pumpkaboo", number: "710"),
//        Pokemon(name: "Gourgeist", number: "711"),
//        Pokemon(name: "Bergmite", number: "712"),
//        Pokemon(name: "Avalugg", number: "713"),
//        Pokemon(name: "Noibat", number: "714"),
//        Pokemon(name: "Noivern", number: "715"),
//        Pokemon(name: "Xerneas", number: "716"),
//        Pokemon(name: "Yveltal", number: "717"),
//        Pokemon(name: "Zygarde", number: "718"),
//        Pokemon(name: "Diancie", number: "719"),
//        Pokemon(name: "Hoopa", number: "720"),
//        Pokemon(name: "Volcanion", number: "721"),
//        Pokemon(name: "Rowlet", number: "722"),
//        Pokemon(name: "Dartrix", number: "723"),
//        Pokemon(name: "Decidueye", number: "724"),
//        Pokemon(name: "Litten", number: "725"),
//        Pokemon(name: "Torracat", number: "726"),
//        Pokemon(name: "Incineroar", number: "727"),
//        Pokemon(name: "Popplio", number: "728"),
//        Pokemon(name: "Brionne", number: "729"),
//        Pokemon(name: "Primarina", number: "730"),
//        Pokemon(name: "Pikipek", number: "731"),
//        Pokemon(name: "Trumbeak", number: "732"),
//        Pokemon(name: "Toucannon", number: "733"),
//        Pokemon(name: "Yungoos", number: "734"),
//        Pokemon(name: "Gumshoos", number: "735"),
//        Pokemon(name: "Grubbin", number: "736"),
//        Pokemon(name: "Charjabug", number: "737"),
//        Pokemon(name: "Vikavolt", number: "738"),
//        Pokemon(name: "Crabrawler", number: "739"),
//        Pokemon(name: "Crabominable", number: "740"),
//        Pokemon(name: "Oricorio", number: "741"),
//        Pokemon(name: "Cutiefly", number: "742"),
//        Pokemon(name: "Ribombee", number: "743"),
//        Pokemon(name: "Rockruff", number: "744"),
//        Pokemon(name: "Lycanroc", number: "745"),
//        Pokemon(name: "Wishiwashi", number: "746"),
//        Pokemon(name: "Mareanie", number: "747"),
//        Pokemon(name: "Toxapex", number: "748"),
//        Pokemon(name: "Mudbray", number: "749"),
//        Pokemon(name: "Mudsdale", number: "750"),
//        Pokemon(name: "Dewpider", number: "751"),
//        Pokemon(name: "Araquanid", number: "752"),
//        Pokemon(name: "Fomantis", number: "753"),
//        Pokemon(name: "Lurantis", number: "754"),
//        Pokemon(name: "Morelull", number: "755"),
//        Pokemon(name: "Shiinotic", number: "756"),
//        Pokemon(name: "Salandit", number: "757"),
//        Pokemon(name: "Salazzle", number: "758"),
//        Pokemon(name: "Stufful", number: "759"),
//        Pokemon(name: "Bewear", number: "760"),
//        Pokemon(name: "Bounsweet", number: "761"),
//        Pokemon(name: "Steenee", number: "762"),
//        Pokemon(name: "Tsareena", number: "763"),
//        Pokemon(name: "Comfey", number: "764"),
//        Pokemon(name: "Oranguru", number: "765"),
//        Pokemon(name: "Passimian", number: "766"),
//        Pokemon(name: "Wimpod", number: "767"),
//        Pokemon(name: "Golisopod", number: "768"),
//        Pokemon(name: "Sandygast", number: "769"),
//        Pokemon(name: "Palossand", number: "770"),
//        Pokemon(name: "Pyukumuku", number: "771"),
//        Pokemon(name: "Type: Null", number: "772"),
//        Pokemon(name: "Silvally", number: "773"),
//        Pokemon(name: "Minior", number: "774"),
//        Pokemon(name: "Komala", number: "775"),
//        Pokemon(name: "Turtonator", number: "776"),
//        Pokemon(name: "Togedemaru", number: "777"),
//        Pokemon(name: "Mimikyu", number: "778"),
//        Pokemon(name: "Bruxish", number: "779"),
//        Pokemon(name: "Drampa", number: "780"),
//        Pokemon(name: "Dhelmise", number: "781"),
//        Pokemon(name: "Jangmo-o", number: "782"),
//        Pokemon(name: "Hakamo-o", number: "783"),
//        Pokemon(name: "Kommo-o", number: "784"),
//        Pokemon(name: "Tapu Koko", number: "785"),
//        Pokemon(name: "Tapu Lele", number: "786"),
//        Pokemon(name: "Tapu Bulu", number: "787"),
//        Pokemon(name: "Tapu Fini", number: "788"),
//        Pokemon(name: "Cosmog", number: "789"),
//        Pokemon(name: "Cosmoem", number: "790"),
//        Pokemon(name: "Solgaleo", number: "791"),
//        Pokemon(name: "Lunala", number: "792"),
//        Pokemon(name: "Nihilego", number: "793"),
//        Pokemon(name: "Buzzwole", number: "794"),
//        Pokemon(name: "Pheromosa", number: "795"),
//        Pokemon(name: "Xurkitree", number: "796"),
//        Pokemon(name: "Celesteela", number: "797"),
//        Pokemon(name: "Kartana", number: "798"),
//        Pokemon(name: "Guzzlord", number: "799"),
//        Pokemon(name: "Necrozma", number: "800"),
//        Pokemon(name: "Magearna", number: "801"),
//        Pokemon(name: "Marshadow", number: "802"),
//        Pokemon(name: "Poipole", number: "803"),
//        Pokemon(name: "Naganadel", number: "804"),
//        Pokemon(name: "Stakataka", number: "805"),
//        Pokemon(name: "Blacephalon", number: "806"),
//        Pokemon(name: "Zeraora", number: "807"),
//        Pokemon(name: "Meltan", number: "808"),
//        Pokemon(name: "Melmetal", number: "809")
        
    ]
}

